"""Deterministic compact Markdown projection of the validated typed inventory."""

from __future__ import annotations

from collections import defaultdict

from model import Inventory


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _table(headers: list[str], rows: list[list[object]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    lines.extend("| " + " | ".join(_cell(value) for value in row) + " |" for row in rows)
    return lines


def render(inventory: Inventory) -> str:
    ledger = inventory.ledger
    gates_by_gap: dict[str, list[str]] = defaultdict(list)
    for gate in ledger["gate_bindings"]:
        for gap in gate["gaps"]:
            gates_by_gap[gap].append(gate["id"])

    lines = [
        "<!-- Generated by: scripts/orphan-inventory.sh write -->",
        "<!-- Typed inputs only. Markdown is output, never inventory authority. -->",
        "",
        "# Typed assurance inventory (Wave 0)",
        "",
        "Status: **machine-generated COMPONENT diagnostic; not Transaction, Live,",
        "Release, receipt, or coordinator authority.** Every runtime profile observed",
        "by this generation remained `BLOCKED`; no absent receipt registry was created.",
        "",
        "This compact projection follows full bidirectional validation of the typed",
        "planning ledger, all corpus units and their code/test subjects, every invariant",
        "and owner, the wire receipt-kind enum, and the real release-command gate union.",
        "A green inventory closes only the declared graph; it completes no wave or gate.",
        "",
        "## Validated coverage",
        "",
        f"- Product gaps: {len(ledger['gaps'])}; waves: {len(ledger['waves'])}; "
        f"V1 slices: {len(ledger['slices'])}; workplan rows: {len(ledger['work_packages'])}.",
        f"- Historical/paper corpus units: {len(inventory.corpus['units'])}; "
        f"resolved test subjects: {inventory.subject_counts['test']}; "
        f"resolved symbol subjects: {inventory.subject_counts['symbol']}.",
        f"- Invariants: {len(inventory.invariants['entries'])}; "
        f"receipt kinds: {len(inventory.receipt_kinds)}.",
        f"- Runtime profiles: {len(ledger['release_profiles'])}; "
        f"runtime gates: {len(ledger['gate_bindings'])}; all returned `BLOCKED`.",
        "",
        "## Gap graph",
        "",
    ]
    gap_rows: list[list[object]] = []
    for gap in ledger["gaps"]:
        routes = list(gates_by_gap[gap["id"]])
        if gap.get("indirect_gate"):
            routes.append(f"indirect → {gap['indirect_gate']}")
        gap_rows.append([
            gap["id"], ", ".join(gap["waves"]), ", ".join(routes), gap["evidence_class"],
        ])
    lines.extend(_table(["Gap", "Waves", "Gate routes", "Current evidence"], gap_rows))
    lines.extend(["", "## Wave graph", ""])
    lines.extend(_table(
        ["Wave", "Depends on", "Gaps", "Slices", "Workplan routes", "Evidence"],
        [
            [
                wave["id"], ", ".join(wave["depends_on"]) or "none",
                ", ".join(wave["gaps"]), ", ".join(wave["slices"]) or "none",
                ", ".join(wave["work_packages"]) or "none", wave["evidence_class"],
            ]
            for wave in ledger["waves"]
        ],
    ))
    lines.extend(["", "## V1 slices", ""])
    lines.extend(_table(
        ["Slice", "Waves", "Current evidence"],
        [[item["id"], ", ".join(item["waves"]), item["evidence_class"]]
         for item in ledger["slices"]],
    ))
    lines.extend(["", "## Workplan routing", ""])
    lines.extend(_table(
        ["Workplan", "Waves", "Follow-on", "Owner", "Lifecycle", "Evidence"],
        [
            [
                item["id"], ", ".join(item["waves"]) or "none",
                ", ".join(item["follow_on"]) or "none", item["owner"],
                item["lifecycle"], item["evidence_class"],
            ]
            for item in ledger["work_packages"]
        ],
    ))
    lines.extend(["", "## Typed source closure", ""])
    lines.extend(_table(
        ["Corpus", "Role", "Units", "Declared path"],
        [
            [
                source["key"], ledger["corpus_roles"][source["key"]],
                inventory.corpus_counts[f"doc:{source['key']}"], source["path"],
            ]
            for source in inventory.corpus["corpus"]
        ],
    ))
    lines.extend([
        "",
        "Corpus dispositions: " + ", ".join(
            f"`{key}` {inventory.corpus_counts[key]}"
            for key in ("IMPLEMENTED", "PLANNED", "REFUSED", "SUPERSEDED")
        ) + ". These are implementation metadata, not evidence promotions.",
        "",
        f"Invariant lifecycles: enforced {inventory.invariant_counts['enforced']}; "
        f"planned {inventory.invariant_counts['planned']}. Every enforced row has a",
        "runtime target and proof command; every row has an owner and first wave.",
        "",
        "Runtime gate classes: " + ", ".join(
            f"`{key}` {inventory.gate_class_counts[key]}"
            for key in ("TRANSACTION", "LIVE", "RELEASE")
        ) + ".",
        "",
        "Receipt-kind reverse edges: " + ", ".join(
            f"`{kind}` {inventory.receipt_kind_counts[kind]}"
            for kind in inventory.receipt_kinds
        ) + ". `release.receipt-contracts` is registry-wide and has no single kind.",
        "",
        "## Exact input digests",
        "",
    ])
    lines.extend(_table(
        ["Typed input", "SHA-256"],
        [[path, value] for path, value in sorted(inventory.source_digests.items())],
    ))
    lines.extend([
        "",
        "## Boundary",
        "",
        "Validation rejects missing, extra, duplicate, stale, zero-partition,",
        "non-bidirectional, unknown-evidence, unknown-owner, absent path/symbol,",
        "unenforced-invariant, receipt-kind, runtime-profile, and runtime-gate drift.",
        "It never reads Markdown as authority or mutates the frozen coordinator.",
        "",
        "Wave 0 remains open until four immutable clean subjects pass standalone and",
        "exact-family proof and this unsigned diagnostic is independently reviewed.",
        "Every release profile remains `BLOCKED` until its semantic verifier passes.",
    ])
    return "\n".join(lines) + "\n"

