use std::fmt::Write as _;

use crate::{Blake3Digest, ContractCatalogV1, FieldTypeV1};

mod template;
use template::RUST_TEMPLATE;

/// Pinned identities every generated binding must carry.
pub(crate) struct BindingInputs<'a> {
    pub(crate) schema: Blake3Digest,
    pub(crate) registry: Blake3Digest,
    pub(crate) policy: Blake3Digest,
    pub(crate) golden_json: &'a str,
    pub(crate) golden_hash: Blake3Digest,
    pub(crate) authority_golden_hash: Blake3Digest,
    pub(crate) launch_grant_golden_hash: Blake3Digest,
    pub(crate) catalog: &'a ContractCatalogV1,
}

pub(crate) fn rust_constants(inputs: &BindingInputs<'_>) -> String {
    let mut output = RUST_TEMPLATE
        .replace("@SCHEMA@", &inputs.schema.to_string())
        .replace("@REGISTRY@", &inputs.registry.to_string())
        .replace("@POLICY@", &inputs.policy.to_string())
        .replace("@GOLDEN_JSON@", inputs.golden_json)
        .replace("@GOLDEN_HASH@", &inputs.golden_hash.to_string())
        .replace(
            "@AUTHORITY_GOLDEN_HASH@",
            &inputs.authority_golden_hash.to_string(),
        )
        .replace(
            "@LAUNCH_GRANT_GOLDEN_HASH@",
            &inputs.launch_grant_golden_hash.to_string(),
        );
    render_rust_records(&mut output, inputs.catalog);
    output
}

pub(crate) fn typescript_constants(inputs: &BindingInputs<'_>) -> String {
    let BindingInputs {
        schema,
        registry,
        policy,
        golden_json,
        golden_hash,
        authority_golden_hash,
        launch_grant_golden_hash,
        catalog,
    } = inputs;
    let encoded_golden = serde_json::to_string(golden_json)
        .expect("a validated canonical JSON string always serializes");
    let mut output = format!(
        "// Generated by: bullet-wire-contract-tool v1alpha1\n\
// Source: contracts/v1alpha1 + policy/v1alpha1\n\
// Command: just contract-generate\n\
// DO NOT EDIT BY HAND.\n\
export const SCHEMA_VERSION = \"v1alpha1\" as const;\n\
export const SCHEMA_BUNDLE_HASH = \"{schema}\" as const;\n\
export const INVARIANT_REGISTRY_HASH = \"{registry}\" as const;\n\
export const POLICY_SNAPSHOT_HASH = \"{policy}\" as const;\n\
export const CANONICAL_GOLDEN_JSON = {encoded_golden} as const;\n\
export const CANONICAL_GOLDEN_HASH = \"{golden_hash}\" as const;\n\
export const AUTHORITY_GOLDEN_HASH = \"{authority_golden_hash}\" as const;\n\
export const LAUNCH_GRANT_GOLDEN_HASH = \"{launch_grant_golden_hash}\" as const;\n\
export type AuthorityAudienceV1 = \"bullet-gitd\" | \"effect-broker\" | \"provider-runner\";\n\
export type MutationOperationV1 = \"clone-workspace\" | \"read-workspace\" | \"apply-patch\" | \"checkpoint\" | \"prepare-candidate\" | \"preserve-workspace\" | \"cleanup-workspace\" | \"dispatch-effect\" | \"reconcile-effect\";\n\
export type AuthorityDecisionV1 = \"authorized\" | \"settled\" | \"refused\";\n\
export type ReplayDispositionV1 = \"fresh\" | \"exact-replay\" | \"conflict\";\n\
export type MutationResultStateV1 = \"in-flight\" | \"committed\" | \"aborted\" | \"unknown\";\n\
export type MutationOutcomeV1 = \"committed\" | \"aborted\" | \"unknown\";\n\
export type SettlementStatusV1 = \"accepted\" | \"exact-replay\" | \"conflict\" | \"refused\";\n\
export type PatchPreimageKindV1 = \"absent\" | \"digest\";\n\
export type PatchMutationKindV1 = \"write\" | \"delete\";\n\
export type ReleaseReceiptKindV1 = \"artifact\" | \"containment\" | \"forge\" | \"operations\" | \"profile-closure\" | \"provider\" | \"rust-toolchain\" | \"scanner\" | \"transaction\";\n\
export type ReleaseEvidenceKindV1 = \"artifact\" | \"audit-anchor\" | \"candidate\" | \"check\" | \"configuration\" | \"effect\" | \"environment\" | \"evidence\" | \"integration\" | \"jeryu\" | \"observation\" | \"platform\" | \"policy\" | \"profile-graph\" | \"proof-bundle\" | \"provider\" | \"provenance\" | \"sandbox\" | \"sbom\" | \"scanner\" | \"schema\" | \"toolchain\" | \"transaction\";\n\
export type ReleaseRegistryObjectKindV1 = \"gate-receipt\" | \"gate-receipt-signature\" | \"gate-spec\" | \"profile-graph\" | \"release-bundle-manifest-v2\" | \"signer-policy\" | \"trusted-time-observation\" | \"trusted-time-signature\" | \"verification-request\";\n\
export type ReleaseSignerRoleV1 = \"artifact-release\" | \"gate-attestor\" | \"registry-curator\" | \"source-tag\" | \"trusted-time\";\n\
export type ReleaseRepositoryNameV1 = \"bullet-farm\" | \"bullet-git\" | \"bullet-kernel\" | \"bullet-portal\";\n\
export type KeyPurposeV1 = \"authority-signing\" | \"release-signing\";\n\
export type KeyAlgorithmV1 = \"paseto-v4.public\" | \"ssh-ed25519\";\n"
    );
    render_typescript_records(&mut output, catalog);
    output
}

fn render_rust_records(output: &mut String, catalog: &ContractCatalogV1) {
    for record in &catalog.records {
        writeln!(
            output,
            "\n#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]\n\
             #[serde(deny_unknown_fields)]\n\
             pub struct {} {{",
            record.name
        )
        .expect("writing to a String cannot fail");
        for field in &record.fields {
            writeln!(
                output,
                "    pub {}: {},",
                field.name,
                rust_type(field.field_type)
            )
            .expect("writing to a String cannot fail");
        }
        output.push_str("}\n");
    }
}

fn render_typescript_records(output: &mut String, catalog: &ContractCatalogV1) {
    for record in &catalog.records {
        writeln!(output, "\nexport interface {} {{", record.name)
            .expect("writing to a String cannot fail");
        for field in &record.fields {
            writeln!(
                output,
                "  {}: {};",
                field.name,
                typescript_type(field.field_type)
            )
            .expect("writing to a String cannot fail");
        }
        output.push_str("}\n");
    }
}

const fn rust_type(field_type: FieldTypeV1) -> &'static str {
    match field_type {
        FieldTypeV1::String
        | FieldTypeV1::SchemaVersion
        | FieldTypeV1::PolicySchemaVersion
        | FieldTypeV1::Identifier
        | FieldTypeV1::Digest
        | FieldTypeV1::OrganizationId
        | FieldTypeV1::RepositoryId
        | FieldTypeV1::MissionId
        | FieldTypeV1::AcceptanceContractId
        | FieldTypeV1::PlanRevisionId
        | FieldTypeV1::GraphRevisionId
        | FieldTypeV1::WorkPackageId
        | FieldTypeV1::SelectionGroupId
        | FieldTypeV1::VariantId
        | FieldTypeV1::AttemptId
        | FieldTypeV1::RunnerId
        | FieldTypeV1::WorkspaceId
        | FieldTypeV1::PrincipalId
        | FieldTypeV1::ProviderProfileId
        | FieldTypeV1::ContentId
        | FieldTypeV1::MutationId
        | FieldTypeV1::MutationReservationId
        | FieldTypeV1::ScopeGrantId
        | FieldTypeV1::SourceDescriptorId
        | FieldTypeV1::ChangeId
        | FieldTypeV1::CheckpointId
        | FieldTypeV1::CandidateId
        | FieldTypeV1::GateReceiptId
        | FieldTypeV1::ReleaseRegistryId
        | FieldTypeV1::GateId
        | FieldTypeV1::EffectIntentId
        | FieldTypeV1::CandidateProofRoot
        | FieldTypeV1::IntegrationProofRoot
        | FieldTypeV1::GitOid
        | FieldTypeV1::TaggedBlake3Digest
        | FieldTypeV1::ReleaseGateId
        | FieldTypeV1::ReleaseNativeSubjectId
        | FieldTypeV1::ReleaseProfileId
        | FieldTypeV1::ReleaseTag
        | FieldTypeV1::SigningIdentity
        | FieldTypeV1::SshEd25519PublicKey
        | FieldTypeV1::RepoPath
        | FieldTypeV1::KeyId
        | FieldTypeV1::PasetoV4Public => "String",
        FieldTypeV1::AuthorityAudience => "AuthorityAudienceV1",
        FieldTypeV1::MutationOperation => "MutationOperationV1",
        FieldTypeV1::AuthorityDecision => "AuthorityDecisionV1",
        FieldTypeV1::ReplayDisposition => "ReplayDispositionV1",
        FieldTypeV1::MutationResultState => "MutationResultStateV1",
        FieldTypeV1::MutationOutcome => "MutationOutcomeV1",
        FieldTypeV1::SettlementStatus => "SettlementStatusV1",
        FieldTypeV1::PatchPreimageKind => "PatchPreimageKindV1",
        FieldTypeV1::PatchMutationKind => "PatchMutationKindV1",
        FieldTypeV1::ReleaseReceiptKind => "ReleaseReceiptKindV1",
        FieldTypeV1::ReleaseEvidenceKind => "ReleaseEvidenceKindV1",
        FieldTypeV1::ReleaseRegistryObjectKind => "ReleaseRegistryObjectKindV1",
        FieldTypeV1::ReleaseSignerRole => "ReleaseSignerRoleV1",
        FieldTypeV1::ReleaseRepositoryName => "ReleaseRepositoryNameV1",
        FieldTypeV1::KeyPurpose => "KeyPurposeV1",
        FieldTypeV1::KeyAlgorithm => "KeyAlgorithmV1",
        FieldTypeV1::U64 | FieldTypeV1::Timestamp => "u64",
        FieldTypeV1::OptionalTimestamp => "Option<u64>",
        FieldTypeV1::OptionalDigest | FieldTypeV1::OptionalString => "Option<String>",
        FieldTypeV1::OptionalMutationReservationId => "Option<String>",
        FieldTypeV1::Boolean => "bool",
        FieldTypeV1::Object => "serde_json::Value",
        FieldTypeV1::StringArray => "Vec<String>",
        FieldTypeV1::ObjectArray => "Vec<serde_json::Value>",
        FieldTypeV1::AuthorityAudienceArray => "Vec<AuthorityAudienceV1>",
        FieldTypeV1::IssuerKeyArray => "Vec<IssuerKeyV1>",
        FieldTypeV1::RiskPolicy => "RiskPolicyV1",
        FieldTypeV1::EvidencePolicy => "EvidencePolicyV1",
        FieldTypeV1::SandboxPolicy => "SandboxPolicyV1",
        FieldTypeV1::BudgetPolicy => "BudgetPolicyV1",
        FieldTypeV1::RoutePolicy => "RoutePolicyV1",
        FieldTypeV1::SignedAuthorityEnvelope => "SignedAuthorityEnvelopeV1",
        FieldTypeV1::SignedMutationPermit => "SignedMutationPermitV1",
        FieldTypeV1::OptionalSignedMutationPermit => "Option<SignedMutationPermitV1>",
        FieldTypeV1::MutationReplayResult => "MutationReplayResultV1",
        FieldTypeV1::OptionalMutationReplayResult => "Option<MutationReplayResultV1>",
        FieldTypeV1::ScopeGrant => "ScopeGrantV1",
        FieldTypeV1::PatchProposal => "PatchProposalV1",
        FieldTypeV1::PatchOperationArray => "Vec<PatchOperationV1>",
        FieldTypeV1::CandidateIdArray
        | FieldTypeV1::GateIdArray
        | FieldTypeV1::ReleaseGateIdArray
        | FieldTypeV1::ReleaseProfileIdArray
        | FieldTypeV1::RepoPathArray => "Vec<String>",
        FieldTypeV1::ReleaseEvidenceKindArray => "Vec<ReleaseEvidenceKindV1>",
        FieldTypeV1::CleanupAuthorization => "CleanupAuthorizationV1",
        FieldTypeV1::ReleaseFamilySubject => "ReleaseFamilySubjectV1",
        FieldTypeV1::ReleaseRepositorySubjectArray => "Vec<ReleaseRepositorySubjectV1>",
        FieldTypeV1::ReleaseEvidenceSubjectArray => "Vec<ReleaseEvidenceSubjectV1>",
        FieldTypeV1::ReleaseProfileNodeArray => "Vec<ReleaseProfileNodeV1>",
        FieldTypeV1::ReleaseSignerKeyArray => "Vec<ReleaseSignerKeyV1>",
        FieldTypeV1::ReleaseRegistryEntryArray => "Vec<ReleaseRegistryEntryV1>",
        FieldTypeV1::ReleaseRegistryObjectArray => "Vec<ReleaseRegistryObjectV1>",
        FieldTypeV1::ReleaseReplayBindingArray => "Vec<ReleaseReplayBindingV1>",
    }
}

const fn typescript_type(field_type: FieldTypeV1) -> &'static str {
    match field_type {
        FieldTypeV1::String
        | FieldTypeV1::SchemaVersion
        | FieldTypeV1::PolicySchemaVersion
        | FieldTypeV1::Identifier
        | FieldTypeV1::Digest
        | FieldTypeV1::OrganizationId
        | FieldTypeV1::RepositoryId
        | FieldTypeV1::MissionId
        | FieldTypeV1::AcceptanceContractId
        | FieldTypeV1::PlanRevisionId
        | FieldTypeV1::GraphRevisionId
        | FieldTypeV1::WorkPackageId
        | FieldTypeV1::SelectionGroupId
        | FieldTypeV1::VariantId
        | FieldTypeV1::AttemptId
        | FieldTypeV1::RunnerId
        | FieldTypeV1::WorkspaceId
        | FieldTypeV1::PrincipalId
        | FieldTypeV1::ProviderProfileId
        | FieldTypeV1::ContentId
        | FieldTypeV1::MutationId
        | FieldTypeV1::MutationReservationId
        | FieldTypeV1::ScopeGrantId
        | FieldTypeV1::SourceDescriptorId
        | FieldTypeV1::ChangeId
        | FieldTypeV1::CheckpointId
        | FieldTypeV1::CandidateId
        | FieldTypeV1::GateReceiptId
        | FieldTypeV1::ReleaseRegistryId
        | FieldTypeV1::GateId
        | FieldTypeV1::EffectIntentId
        | FieldTypeV1::CandidateProofRoot
        | FieldTypeV1::IntegrationProofRoot
        | FieldTypeV1::GitOid
        | FieldTypeV1::TaggedBlake3Digest
        | FieldTypeV1::ReleaseGateId
        | FieldTypeV1::ReleaseNativeSubjectId
        | FieldTypeV1::ReleaseProfileId
        | FieldTypeV1::ReleaseTag
        | FieldTypeV1::SigningIdentity
        | FieldTypeV1::SshEd25519PublicKey
        | FieldTypeV1::RepoPath
        | FieldTypeV1::KeyId
        | FieldTypeV1::PasetoV4Public => "string",
        FieldTypeV1::AuthorityAudience => "AuthorityAudienceV1",
        FieldTypeV1::MutationOperation => "MutationOperationV1",
        FieldTypeV1::AuthorityDecision => "AuthorityDecisionV1",
        FieldTypeV1::ReplayDisposition => "ReplayDispositionV1",
        FieldTypeV1::MutationResultState => "MutationResultStateV1",
        FieldTypeV1::MutationOutcome => "MutationOutcomeV1",
        FieldTypeV1::SettlementStatus => "SettlementStatusV1",
        FieldTypeV1::PatchPreimageKind => "PatchPreimageKindV1",
        FieldTypeV1::PatchMutationKind => "PatchMutationKindV1",
        FieldTypeV1::ReleaseReceiptKind => "ReleaseReceiptKindV1",
        FieldTypeV1::ReleaseEvidenceKind => "ReleaseEvidenceKindV1",
        FieldTypeV1::ReleaseRegistryObjectKind => "ReleaseRegistryObjectKindV1",
        FieldTypeV1::ReleaseSignerRole => "ReleaseSignerRoleV1",
        FieldTypeV1::ReleaseRepositoryName => "ReleaseRepositoryNameV1",
        FieldTypeV1::KeyPurpose => "KeyPurposeV1",
        FieldTypeV1::KeyAlgorithm => "KeyAlgorithmV1",
        FieldTypeV1::U64 | FieldTypeV1::Timestamp => "number",
        FieldTypeV1::OptionalTimestamp => "number | null",
        FieldTypeV1::OptionalDigest
        | FieldTypeV1::OptionalString
        | FieldTypeV1::OptionalMutationReservationId => "string | null",
        FieldTypeV1::Boolean => "boolean",
        FieldTypeV1::Object => "Record<string, unknown>",
        FieldTypeV1::StringArray => "string[]",
        FieldTypeV1::ObjectArray => "Record<string, unknown>[]",
        FieldTypeV1::AuthorityAudienceArray => "AuthorityAudienceV1[]",
        FieldTypeV1::IssuerKeyArray => "IssuerKeyV1[]",
        FieldTypeV1::RiskPolicy => "RiskPolicyV1",
        FieldTypeV1::EvidencePolicy => "EvidencePolicyV1",
        FieldTypeV1::SandboxPolicy => "SandboxPolicyV1",
        FieldTypeV1::BudgetPolicy => "BudgetPolicyV1",
        FieldTypeV1::RoutePolicy => "RoutePolicyV1",
        FieldTypeV1::SignedAuthorityEnvelope => "SignedAuthorityEnvelopeV1",
        FieldTypeV1::SignedMutationPermit => "SignedMutationPermitV1",
        FieldTypeV1::OptionalSignedMutationPermit => "SignedMutationPermitV1 | null",
        FieldTypeV1::MutationReplayResult => "MutationReplayResultV1",
        FieldTypeV1::OptionalMutationReplayResult => "MutationReplayResultV1 | null",
        FieldTypeV1::ScopeGrant => "ScopeGrantV1",
        FieldTypeV1::PatchProposal => "PatchProposalV1",
        FieldTypeV1::PatchOperationArray => "PatchOperationV1[]",
        FieldTypeV1::CandidateIdArray
        | FieldTypeV1::GateIdArray
        | FieldTypeV1::ReleaseGateIdArray
        | FieldTypeV1::ReleaseProfileIdArray
        | FieldTypeV1::RepoPathArray => "string[]",
        FieldTypeV1::ReleaseEvidenceKindArray => "ReleaseEvidenceKindV1[]",
        FieldTypeV1::CleanupAuthorization => "CleanupAuthorizationV1",
        FieldTypeV1::ReleaseFamilySubject => "ReleaseFamilySubjectV1",
        FieldTypeV1::ReleaseRepositorySubjectArray => "ReleaseRepositorySubjectV1[]",
        FieldTypeV1::ReleaseEvidenceSubjectArray => "ReleaseEvidenceSubjectV1[]",
        FieldTypeV1::ReleaseProfileNodeArray => "ReleaseProfileNodeV1[]",
        FieldTypeV1::ReleaseSignerKeyArray => "ReleaseSignerKeyV1[]",
        FieldTypeV1::ReleaseRegistryEntryArray => "ReleaseRegistryEntryV1[]",
        FieldTypeV1::ReleaseRegistryObjectArray => "ReleaseRegistryObjectV1[]",
        FieldTypeV1::ReleaseReplayBindingArray => "ReleaseReplayBindingV1[]",
    }
}
