//! Public module boundary for the Hub-generated wire contract.
//!
//! Generated bytes live outside protected authored source so automation cannot
//! rewrite product logic while synchronizing the family contract.

include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../contracts/generated/rust/schema_bundle.rs"
));
