pub(super) const RUST_TEMPLATE: &str = r###"// Generated by: bullet-wire-contract-tool v1alpha1
// Source: contracts/v1alpha1 + policy/v1alpha1
// Command: just contract-generate
// DO NOT EDIT BY HAND.
pub const SCHEMA_VERSION: &str = "v1alpha1";
pub const SCHEMA_BUNDLE_HASH: &str =
    "@SCHEMA@";
pub const INVARIANT_REGISTRY_HASH: &str =
    "@REGISTRY@";
pub const POLICY_SNAPSHOT_HASH: &str =
    "@POLICY@";
pub const CANONICAL_GOLDEN_JSON: &str = r##"@GOLDEN_JSON@"##;
pub const CANONICAL_GOLDEN_HASH: &str =
    "@GOLDEN_HASH@";
pub const AUTHORITY_GOLDEN_HASH: &str =
    "@AUTHORITY_GOLDEN_HASH@";
pub const LAUNCH_GRANT_GOLDEN_HASH: &str =
    "@LAUNCH_GRANT_GOLDEN_HASH@";

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AuthorityAudienceV1 {
    BulletGitd,
    EffectBroker,
    ProviderRunner,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum MutationOperationV1 {
    CloneWorkspace,
    ReadWorkspace,
    ApplyPatch,
    Checkpoint,
    PrepareCandidate,
    PreserveWorkspace,
    CleanupWorkspace,
    DispatchEffect,
    ReconcileEffect,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AuthorityDecisionV1 {
    Authorized,
    Settled,
    Refused,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ReplayDispositionV1 {
    Fresh,
    ExactReplay,
    Conflict,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum MutationResultStateV1 {
    InFlight,
    Committed,
    Aborted,
    Unknown,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum MutationOutcomeV1 {
    Committed,
    Aborted,
    Unknown,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SettlementStatusV1 {
    Accepted,
    ExactReplay,
    Conflict,
    Refused,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum PatchPreimageKindV1 {
    Absent,
    Digest,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum PatchMutationKindV1 {
    Write,
    Delete,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ReleaseReceiptKindV1 {
    Artifact,
    Containment,
    Forge,
    Operations,
    ProfileClosure,
    Provider,
    RustToolchain,
    Scanner,
    Transaction,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ReleaseEvidenceKindV1 {
    Artifact,
    AuditAnchor,
    Candidate,
    Check,
    Configuration,
    Effect,
    Environment,
    Evidence,
    Integration,
    Jeryu,
    Observation,
    Platform,
    Policy,
    ProfileGraph,
    ProofBundle,
    Provider,
    Provenance,
    Sandbox,
    Sbom,
    Scanner,
    Schema,
    Toolchain,
    Transaction,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ReleaseRegistryObjectKindV1 {
    GateReceipt,
    GateReceiptSignature,
    GateSpec,
    ProfileGraph,
    ReleaseBundleManifestV2,
    SignerPolicy,
    TrustedTimeObservation,
    TrustedTimeSignature,
    VerificationRequest,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ReleaseSignerRoleV1 {
    ArtifactRelease,
    GateAttestor,
    RegistryCurator,
    SourceTag,
    TrustedTime,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ReleaseRepositoryNameV1 {
    BulletFarm,
    BulletGit,
    BulletKernel,
    BulletPortal,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum KeyPurposeV1 {
    AuthoritySigning,
    ReleaseSigning,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum KeyAlgorithmV1 {
    #[serde(rename = "paseto-v4.public")]
    PasetoV4Public,
    #[serde(rename = "ssh-ed25519")]
    SshEd25519,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PinnedContract {
    SchemaBundle,
    InvariantRegistry,
    PolicySnapshot,
    CanonicalGolden,
}

impl PinnedContract {
    fn identity(self) -> (&'static str, &'static str) {
        match self {
            Self::SchemaBundle => ("schema.bundle", SCHEMA_BUNDLE_HASH),
            Self::InvariantRegistry => ("invariant.registry", INVARIANT_REGISTRY_HASH),
            Self::PolicySnapshot => ("policy.snapshot", POLICY_SNAPSHOT_HASH),
            Self::CanonicalGolden => ("golden.cross-language", CANONICAL_GOLDEN_HASH),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ContractPinError {
    document: &'static str,
}

impl ContractPinError {
    #[must_use]
    pub const fn reason_code(&self) -> &'static str {
        "UNPINNED_CONTRACT"
    }

    #[must_use]
    pub const fn document(&self) -> &'static str {
        self.document
    }
}

impl std::fmt::Display for ContractPinError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "{} bytes do not match the pinned identity",
            self.document
        )
    }
}

impl std::error::Error for ContractPinError {}

pub fn verify_pinned_contract(
    contract: PinnedContract,
    bytes: &[u8],
) -> Result<(), ContractPinError> {
    let (domain, expected) = contract.identity();
    let mut hasher = blake3::Hasher::new();
    hasher.update(b"bullet-wire.v1\0");
    update_frame(&mut hasher, domain.as_bytes());
    update_frame(&mut hasher, bytes);
    let actual = hasher.finalize().to_hex();
    if actual.as_str() == expected {
        Ok(())
    } else {
        Err(ContractPinError { document: domain })
    }
}

fn update_frame(hasher: &mut blake3::Hasher, bytes: &[u8]) {
    hasher.update(&(bytes.len() as u64).to_le_bytes());
    hasher.update(bytes);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn golden_pin_rejects_any_byte_or_domain_change() {
        verify_pinned_contract(
            PinnedContract::CanonicalGolden,
            CANONICAL_GOLDEN_JSON.as_bytes(),
        )
        .unwrap();

        let mut changed = CANONICAL_GOLDEN_JSON.as_bytes().to_vec();
        changed.push(b' ');
        let error = verify_pinned_contract(PinnedContract::CanonicalGolden, &changed).unwrap_err();
        assert_eq!(error.reason_code(), "UNPINNED_CONTRACT");
        assert_eq!(error.document(), "golden.cross-language");
        assert!(verify_pinned_contract(
            PinnedContract::SchemaBundle,
            CANONICAL_GOLDEN_JSON.as_bytes(),
        )
        .is_err());
    }
}
"###;
