//! Release truth (shift brief): the exact claims that remain unproved, rendered
//! from machine facts only. The page is a projection; it never changes a gate.

mod facts;
mod render;
mod rows;

use std::path::Path;

use super::model::CheckReport;
use crate::coord::CoordError;
pub(super) use facts::Variant;

pub(super) fn render(
    hub: &Path,
    report: &CheckReport,
    variant: Variant,
) -> Result<String, CoordError> {
    let facts = facts::gather(hub, variant);
    render::render(&facts, report)
}

#[cfg(test)]
mod tests {
    use super::{
        facts::{
            Facts, InputFact, Mechanical, MechanicalFact, Register, ReleaseIndexFact, SubjectFact,
        },
        *,
    };
    use crate::{check::prerequisites, doctor::LockSummary};

    const REGISTER_PATH: &str = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/docs/assurance/product-gaps.md"
    );

    fn hub_register() -> String {
        std::fs::read_to_string(REGISTER_PATH).expect("product gap register")
    }

    fn synthetic(variant: Variant) -> Facts {
        let live = variant == Variant::Live;
        Facts {
            variant,
            hub_root: live.then(|| "/fixture/bullet-farm".to_owned()),
            subjects: vec![
                SubjectFact {
                    name: "bullet-farm",
                    commit: Some(format!("sha1:{}", "a".repeat(40))),
                    tree: Some(format!("sha1:{}", "b".repeat(40))),
                    checkout: "clean".to_owned(),
                },
                SubjectFact {
                    name: "bullet-kernel",
                    commit: None,
                    tree: None,
                    checkout: "absent".to_owned(),
                },
            ],
            hub_head_committed_at: live.then(|| "2026-01-02T03:04:05+00:00".to_owned()),
            lock: Ok(LockSummary {
                schema_version: "2".to_owned(),
                tag: "v0.0.0-fixture".to_owned(),
                installable: false,
                members: vec![
                    ("bullet-farm".to_owned(), "a".repeat(40)),
                    ("bullet-kernel".to_owned(), "c".repeat(40)),
                ],
            }),
            release_index: ReleaseIndexFact {
                status: Some("BLOCKED".to_owned()),
                last_reviewed: Some("2026-01-01".to_owned()),
            },
            register: facts::parse_register(&hub_register()),
            mechanical: vec![
                MechanicalFact {
                    tier: "fast",
                    path: ".bullet-family/check-fast.json",
                    outcome: Mechanical::Stale {
                        status: "PASS".to_owned(),
                        gates: 7,
                        mismatch: "bullet-farm recorded sha1:0, HEAD sha1:a".to_owned(),
                    },
                },
                MechanicalFact {
                    tier: "required",
                    path: ".bullet-family/check-required.json",
                    outcome: Mechanical::Absent,
                },
            ],
            inputs: vec![InputFact {
                label: "family lock",
                path: "family.lock",
                identity: format!("blake3:{}", "d".repeat(64)),
                mtime: live.then(|| "1700000000".to_owned()),
            }],
        }
    }

    fn section<'a>(page: &'a str, start: &str, end: &str) -> &'a str {
        let (_, rest) = page.split_once(start).unwrap();
        rest.split_once(end).unwrap().0
    }

    fn claim_lines(section: &str) -> Vec<&str> {
        section
            .lines()
            .filter(|line| {
                line.contains("**")
                    || line.contains("- Why it matters:")
                    || line.contains("- Acceptance:")
            })
            .collect()
    }

    #[test]
    fn rendering_is_deterministic_and_keeps_the_five_truths_apart() {
        let report = prerequisites::report_release().unwrap();
        for variant in [Variant::Live, Variant::Portable] {
            let facts = synthetic(variant);
            let first = render::render(&facts, &report).unwrap();
            let second = render::render(&facts, &report).unwrap();
            assert_eq!(first, second);
            assert!(first.starts_with(
                "<!-- Generated by: bullet-family check release --profile PROFILE_REQUIRED --receipts ABSOLUTE_REGISTRY --report"
            ));
            assert!(first.contains("\nRELEASE DECISION: BLOCKED\n"));
            for truth in [
                "| Mechanical gates (fast) | STALE — PASS over 7 gates",
                "| Mechanical gates (required) | NOT RUN",
                "| Evidence completeness | 0 of 28 receipted |",
                "| Release review | HOLD",
                "| Deployment match | N/A",
                "| Post-deploy survival | NOT ESTABLISHED |",
            ] {
                assert!(first.contains(truth), "{variant:?} lacks {truth}");
            }
            assert!(first.contains("| bullet-kernel | UNKNOWN | UNKNOWN | absent |"));
            assert!(first.contains("| tag | `v0.0.0-fixture` |"));
            assert!(!first.ends_with('\n'));
            assert_eq!(first.matches("   - Release-blocking: yes\n").count(), 28);
            assert_eq!(first.matches("   - Product gap: G").count(), 28);
            assert_eq!(
                first.matches("   - Next command: ").count(),
                28 + rows::UNGATED.len()
            );
            assert!(first.contains("Agreement with `docs/assurance/product-gaps.md`: YES — all 46 crosswalk rows and the G-id list agree"));
            assert!(first.contains(
                "| G12 | Family `check release` | this `unprofiled` inventory — 28 selected gates, 0 receipted"
            ));
            assert!(first.contains("| G4 | Production BulletGit write path | ungated — release-blocking through the selected `release.transaction-demo`; see below"));
        }
        let live = render::render(&synthetic(Variant::Live), &report).unwrap();
        assert!(live.contains("| hub | `/fixture/bullet-farm` |"));
        assert!(live.contains("NO — bullet-kernel locked `ccc"));
        assert!(live.contains("hub HEAD committed 2026-01-02T03:04:05+00:00"));
        let portable = render::render(&synthetic(Variant::Portable), &report).unwrap();
        assert!(!portable.contains("/fixture/"));
        assert!(!portable.contains("1700000000"));
        assert!(portable.contains("| binds current HEADs | UNKNOWN (portable variant"));
    }

    #[test]
    fn rendered_claim_blocks_never_read_as_closed() {
        let report = prerequisites::report_release().unwrap();
        let page = render::render(&synthetic(Variant::Portable), &report).unwrap();
        let gates = section(&page, "## Gates", render::CROSSWALK_HEADING);
        let ungated = section(&page, render::UNGATED_HEADING, "## Excluded");
        let mut blocks = 0;
        for line in claim_lines(gates).into_iter().chain(claim_lines(ungated)) {
            assert!(
                !rows::contains_closed_word(line),
                "closed vocabulary: {line}"
            );
            blocks += 1;
        }
        assert_eq!(blocks, (28 + rows::UNGATED.len()) * 3);
        for line in page.lines().filter(|line| line.starts_with("   - Owner: ")) {
            let owner = line.trim_start_matches("   - Owner: ");
            assert!(
                rows::Owner::LABELS
                    .iter()
                    .any(|label| owner.starts_with(&format!("{label} ("))),
                "owner outside the closed vocabulary: {line}"
            );
        }
        for line in page
            .lines()
            .filter(|line| line.starts_with("   - Next command: "))
        {
            let next = line.trim_start_matches("   - Next command: ");
            assert!(
                next.starts_with('`') || next.starts_with(rows::Next::NONE_LABEL),
                "next command is neither typed nor honestly absent: {line}"
            );
        }
    }

    #[test]
    fn register_drift_is_reported_not_hidden() {
        let report = prerequisites::report_release().unwrap();
        let drifted = hub_register().replace(
            "| `release.backup-restore` | G3, G9 |",
            "| `release.backup-restore` | G9 |",
        );
        let mut facts = synthetic(Variant::Portable);
        facts.register = facts::parse_register(&drifted);
        let page = render::render(&facts, &report).unwrap();
        assert!(page.contains(
            "Agreement with `docs/assurance/product-gaps.md`: NO — `release.backup-restore`: page G3, G9 vs register G9"
        ));
        facts.register = Register::Absent;
        let page = render::render(&facts, &report).unwrap();
        assert!(page.contains(
            "Agreement with `docs/assurance/product-gaps.md`: UNKNOWN — the register is absent"
        ));
    }

    #[test]
    fn hub_register_crosswalk_and_titles_match_the_compiled_rows() {
        let Register::Read(table) = facts::parse_register(&hub_register()) else {
            panic!("hub register did not parse");
        };
        assert_eq!(table.gates.len(), rows::row_count());
        for row in rows::all_rows() {
            let (_, ids) = table
                .gates
                .iter()
                .find(|(gate, _)| gate == row.id)
                .unwrap_or_else(|| panic!("{} missing from the register", row.id));
            assert_eq!(ids, row.gap_ids, "{} crosswalk drifted", row.id);
        }
        let compiled = rows::PRODUCT_GAPS
            .iter()
            .map(|(id, _)| *id)
            .collect::<Vec<_>>();
        assert_eq!(table.gap_ids, compiled);
        let text = hub_register();
        for &(id, title) in rows::PRODUCT_GAPS {
            let expected = format!("| {id} | {title} |");
            assert!(
                text.contains(&expected),
                "register title drifted for {id}: {expected}"
            );
        }
        assert_eq!(
            facts::parse_register("no tables here"),
            Register::Unparsed("no `release.*` crosswalk rows".to_owned())
        );
    }
}
