use crate::{
    Blake3Digest, FieldTypeV1, WireError,
    catalog::{
        LegacyReferenceShapeV1, ResolvedCatalogV1, ResolvedFieldKindV1, ResolvedFieldV1,
        ScalarDefinitionV1, rust_variant_identifier,
    },
};

mod strict;
mod strict_template;
mod template;
use template::RUST_TEMPLATE;

#[cfg(test)]
mod tests;

/// Pinned identities every generated binding must carry.
pub(crate) struct BindingInputs<'input, 'catalog> {
    pub(crate) schema: Blake3Digest,
    pub(crate) registry: Blake3Digest,
    pub(crate) policy: Blake3Digest,
    pub(crate) golden_json: &'input str,
    pub(crate) golden_hash: Blake3Digest,
    pub(crate) authority_golden_hash: Blake3Digest,
    pub(crate) launch_grant_golden_hash: Blake3Digest,
    pub(crate) resolved: &'input ResolvedCatalogV1<'catalog>,
}

#[rustfmt::skip]
pub(crate) fn rust_constants(inputs: &BindingInputs<'_, '_>) -> Result<String, WireError> {
    let mut output = RUST_TEMPLATE
        .replace("@SCHEMA@", &inputs.schema.to_string())
        .replace("@REGISTRY@", &inputs.registry.to_string())
        .replace("@POLICY@", &inputs.policy.to_string())
        .replace("@GOLDEN_JSON@", inputs.golden_json)
        .replace("@GOLDEN_HASH@", &inputs.golden_hash.to_string())
        .replace("@AUTHORITY_GOLDEN_HASH@", &inputs.authority_golden_hash.to_string())
        .replace("@LAUNCH_GRANT_GOLDEN_HASH@", &inputs.launch_grant_golden_hash.to_string());
    if strict::is_required(inputs.resolved) {
        strict::render_rust(&mut output, inputs.resolved)?;
    } else {
        render_legacy_rust_records(&mut output, inputs.resolved)?;
    }
    Ok(output)
}

#[rustfmt::skip]
pub(crate) fn typescript_constants(inputs: &BindingInputs<'_, '_>) -> Result<String, WireError> {
    let BindingInputs { schema, registry, policy, golden_json, golden_hash, authority_golden_hash, launch_grant_golden_hash, resolved } = inputs;
    let encoded_golden = serde_json::to_string(golden_json).map_err(|error| {
        WireError::new("INVALID_CONTRACT_FIELD_REFERENCE", format!("canonical golden cannot be encoded: {error}"))
    })?;
    let mut output = format!(
        "// Generated by: bullet-wire-contract-tool v1alpha1\n\
// Source: contracts/v1alpha1 + policy/v1alpha1\n\
// Command: just contract-generate\n\
// DO NOT EDIT BY HAND.\n\
export const SCHEMA_VERSION = \"v1alpha1\" as const;\n\
export const SCHEMA_BUNDLE_HASH = \"{schema}\" as const;\n\
export const INVARIANT_REGISTRY_HASH = \"{registry}\" as const;\n\
export const POLICY_SNAPSHOT_HASH = \"{policy}\" as const;\n\
export const CANONICAL_GOLDEN_JSON = {encoded_golden} as const;\n\
export const CANONICAL_GOLDEN_HASH = \"{golden_hash}\" as const;\n\
export const AUTHORITY_GOLDEN_HASH = \"{authority_golden_hash}\" as const;\n\
export const LAUNCH_GRANT_GOLDEN_HASH = \"{launch_grant_golden_hash}\" as const;\n\
export type AuthorityAudienceV1 = \"bullet-gitd\" | \"effect-broker\" | \"provider-runner\";\n\
export type MutationOperationV1 = \"clone-workspace\" | \"read-workspace\" | \"apply-patch\" | \"checkpoint\" | \"prepare-candidate\" | \"preserve-workspace\" | \"cleanup-workspace\" | \"dispatch-effect\" | \"reconcile-effect\";\n\
export type AuthorityDecisionV1 = \"authorized\" | \"settled\" | \"refused\";\n\
export type ReplayDispositionV1 = \"fresh\" | \"exact-replay\" | \"conflict\";\n\
export type MutationResultStateV1 = \"in-flight\" | \"committed\" | \"aborted\" | \"unknown\";\n\
export type MutationOutcomeV1 = \"committed\" | \"aborted\" | \"unknown\";\n\
export type SettlementStatusV1 = \"accepted\" | \"exact-replay\" | \"conflict\" | \"refused\";\n\
export type PatchPreimageKindV1 = \"absent\" | \"digest\";\n\
export type PatchMutationKindV1 = \"write\" | \"delete\";\n\
export type ReleaseReceiptKindV1 = \"artifact\" | \"containment\" | \"forge\" | \"operations\" | \"profile-closure\" | \"provider\" | \"rust-toolchain\" | \"scanner\" | \"transaction\";\n\
export type ReleaseEvidenceKindV1 = \"artifact\" | \"audit-anchor\" | \"candidate\" | \"check\" | \"configuration\" | \"effect\" | \"environment\" | \"evidence\" | \"integration\" | \"jeryu\" | \"observation\" | \"platform\" | \"policy\" | \"profile-graph\" | \"proof-bundle\" | \"provider\" | \"provenance\" | \"sandbox\" | \"sbom\" | \"scanner\" | \"schema\" | \"toolchain\" | \"transaction\";\n\
export type ReleaseRegistryObjectKindV1 = \"gate-receipt\" | \"gate-receipt-signature\" | \"gate-spec\" | \"profile-graph\" | \"release-bundle-manifest-v2\" | \"signer-policy\" | \"trusted-time-observation\" | \"trusted-time-signature\" | \"verification-request\";\n\
export type ReleaseSignerRoleV1 = \"artifact-release\" | \"gate-attestor\" | \"registry-curator\" | \"source-tag\" | \"trusted-time\";\n\
export type ReleaseRepositoryNameV1 = \"bullet-farm\" | \"bullet-git\" | \"bullet-kernel\" | \"bullet-portal\";\n\
export type KeyPurposeV1 = \"authority-signing\" | \"release-signing\";\n\
export type KeyAlgorithmV1 = \"paseto-v4.public\" | \"ssh-ed25519\";\n"
    );
    if strict::is_required(resolved) {
        strict::render_typescript(&mut output, resolved)?;
    } else {
        render_legacy_typescript_records(&mut output, resolved)?;
    }
    Ok(output)
}

#[rustfmt::skip]
fn render_legacy_rust_records(output: &mut String, resolved: &ResolvedCatalogV1<'_>) -> Result<(), WireError> {
    for record in resolved.records() {
        output.push_str(&format!("\n#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]\n#[serde(deny_unknown_fields)]\npub struct {} {{\n", record.definition().name));
        for field in record.fields() {
            output.push_str(&format!("    pub {}: {},\n", field.definition().name, rust_type(field)?));
        }
        output.push_str("}\n");
    }
    Ok(())
}

#[rustfmt::skip]
fn render_legacy_typescript_records(output: &mut String, resolved: &ResolvedCatalogV1<'_>) -> Result<(), WireError> {
    for record in resolved.records() {
        output.push_str(&format!("\nexport interface {} {{\n", record.definition().name));
        for field in record.fields() {
            output.push_str(&format!("  {}: {};\n", field.definition().name, typescript_type(field)?));
        }
        output.push_str("}\n");
    }
    Ok(())
}

#[rustfmt::skip]
fn rust_type(field: &ResolvedFieldV1<'_>) -> Result<String, WireError> {
    match field.kind() {
        ResolvedFieldKindV1::LegacyValue => legacy_types(field.definition().field_type).map(|types| types.0.to_owned()).ok_or_else(impossible_field),
        ResolvedFieldKindV1::LegacyReference { shape, target } => {
            ensure_reference_shape(field.definition().field_type, shape)?;
            Ok(match shape { LegacyReferenceShapeV1::Direct => target.name().into(), LegacyReferenceShapeV1::Optional => format!("Option<{}>", target.name()), LegacyReferenceShapeV1::Array => format!("Vec<{}>", target.name()) })
        }
        ResolvedFieldKindV1::Named(_) | ResolvedFieldKindV1::OptionalNamed(_) | ResolvedFieldKindV1::BoundedArray { .. } | ResolvedFieldKindV1::BoundedSet { .. } => Err(impossible_field()),
    }
}

#[rustfmt::skip]
fn typescript_type(field: &ResolvedFieldV1<'_>) -> Result<String, WireError> {
    match field.kind() {
        ResolvedFieldKindV1::LegacyValue => legacy_types(field.definition().field_type).map(|types| types.1.to_owned()).ok_or_else(impossible_field),
        ResolvedFieldKindV1::LegacyReference { shape, target } => {
            ensure_reference_shape(field.definition().field_type, shape)?;
            Ok(match shape { LegacyReferenceShapeV1::Direct => target.name().into(), LegacyReferenceShapeV1::Optional => format!("{} | null", target.name()), LegacyReferenceShapeV1::Array => format!("{}[]", target.name()) })
        }
        ResolvedFieldKindV1::Named(_) | ResolvedFieldKindV1::OptionalNamed(_) | ResolvedFieldKindV1::BoundedArray { .. } | ResolvedFieldKindV1::BoundedSet { .. } => Err(impossible_field()),
    }
}

#[rustfmt::skip]
const fn legacy_types(field_type: FieldTypeV1) -> Option<(&'static str, &'static str)> {
    use FieldTypeV1::*;
    Some(match field_type {
        String | SchemaVersion | PolicySchemaVersion | Identifier | Digest | OrganizationId | RepositoryId | MissionId | AcceptanceContractId | PlanRevisionId | GraphRevisionId | WorkPackageId | SelectionGroupId | VariantId | AttemptId | RunnerId | WorkspaceId | PrincipalId | ProviderProfileId | ContentId | MutationId | MutationReservationId | ScopeGrantId | SourceDescriptorId | ChangeId | CheckpointId | CandidateId | GateReceiptId | ReleaseRegistryId | GateId | EffectIntentId | CandidateProofRoot | IntegrationProofRoot | GitOid | TaggedBlake3Digest | ReleaseGateId | ReleaseNativeSubjectId | ReleaseProfileId | ReleaseTag | SigningIdentity | SshEd25519PublicKey | RepoPath | KeyId | PasetoV4Public => ("String", "string"),
        AuthorityAudience => ("AuthorityAudienceV1", "AuthorityAudienceV1"), MutationOperation => ("MutationOperationV1", "MutationOperationV1"), AuthorityDecision => ("AuthorityDecisionV1", "AuthorityDecisionV1"), ReplayDisposition => ("ReplayDispositionV1", "ReplayDispositionV1"), MutationResultState => ("MutationResultStateV1", "MutationResultStateV1"), MutationOutcome => ("MutationOutcomeV1", "MutationOutcomeV1"), SettlementStatus => ("SettlementStatusV1", "SettlementStatusV1"), PatchPreimageKind => ("PatchPreimageKindV1", "PatchPreimageKindV1"), PatchMutationKind => ("PatchMutationKindV1", "PatchMutationKindV1"), ReleaseReceiptKind => ("ReleaseReceiptKindV1", "ReleaseReceiptKindV1"), ReleaseEvidenceKind => ("ReleaseEvidenceKindV1", "ReleaseEvidenceKindV1"), ReleaseRegistryObjectKind => ("ReleaseRegistryObjectKindV1", "ReleaseRegistryObjectKindV1"), ReleaseSignerRole => ("ReleaseSignerRoleV1", "ReleaseSignerRoleV1"), ReleaseRepositoryName => ("ReleaseRepositoryNameV1", "ReleaseRepositoryNameV1"), KeyPurpose => ("KeyPurposeV1", "KeyPurposeV1"), KeyAlgorithm => ("KeyAlgorithmV1", "KeyAlgorithmV1"),
        SafeU64 | U64 | Timestamp => ("u64", "number"), OptionalTimestamp => ("Option<u64>", "number | null"), OptionalDigest | OptionalString | OptionalMutationReservationId => ("Option<String>", "string | null"), Boolean => ("bool", "boolean"), Object => ("serde_json::Value", "Record<string, unknown>"), StringArray => ("Vec<String>", "string[]"), ObjectArray => ("Vec<serde_json::Value>", "Record<string, unknown>[]"), AuthorityAudienceArray => ("Vec<AuthorityAudienceV1>", "AuthorityAudienceV1[]"), CandidateIdArray | OrderedCandidateIdArray | GateIdArray | ReleaseGateIdArray | ReleaseProfileIdArray | RepoPathArray => ("Vec<String>", "string[]"), ReleaseEvidenceKindArray => ("Vec<ReleaseEvidenceKindV1>", "ReleaseEvidenceKindV1[]"),
        IssuerKeyArray | RiskPolicy | EvidencePolicy | SandboxPolicy | BudgetPolicy | RoutePolicy | SignedAuthorityEnvelope | SignedMutationPermit | OptionalSignedMutationPermit | MutationReplayResult | OptionalMutationReplayResult | ScopeGrant | PatchProposal | PatchOperationArray | CleanupAuthorization | ReleaseFamilySubject | ReleaseRepositorySubjectArray | ReleaseEvidenceSubjectArray | ReleaseProfileNodeArray | ReleaseSignerKeyArray | ReleaseRegistryEntryArray | ReleaseRegistryObjectArray | ReleaseReplayBindingArray | ExecutionToolArray | NamedRef | OptionalNamedRef | BoundedArray | BoundedSet => return None,
    })
}

#[rustfmt::skip]
fn ensure_reference_shape(field_type: FieldTypeV1, shape: LegacyReferenceShapeV1) -> Result<(), WireError> {
    use FieldTypeV1::*;
    use LegacyReferenceShapeV1::{Array, Direct, Optional};
    let actual = match field_type {
        RiskPolicy | EvidencePolicy | SandboxPolicy | BudgetPolicy | RoutePolicy | SignedAuthorityEnvelope | SignedMutationPermit | MutationReplayResult | ScopeGrant | PatchProposal | CleanupAuthorization | ReleaseFamilySubject => Some(Direct),
        OptionalSignedMutationPermit | OptionalMutationReplayResult => Some(Optional),
        IssuerKeyArray | PatchOperationArray | ReleaseRepositorySubjectArray | ReleaseEvidenceSubjectArray | ReleaseProfileNodeArray | ReleaseSignerKeyArray | ReleaseRegistryEntryArray | ReleaseRegistryObjectArray | ReleaseReplayBindingArray | ExecutionToolArray => Some(Array),
        _ => None,
    };
    if actual == Some(shape) { Ok(()) } else { Err(impossible_field()) }
}

#[rustfmt::skip]
fn impossible_field() -> WireError {
    WireError::new("INVALID_CONTRACT_FIELD_REFERENCE", "resolved field kind contradicts its private raw field kind")
}

#[rustfmt::skip]
#[derive(Default)]
struct StrictFeatures {
    arrays: bool, boolean: bool, bounds: bool, bounded_array: bool, bounded_set: bool,
    collect_array: bool, integer: bool, legacy_string: bool, pattern: bool, rebase: bool, set: bool,
    string: bool, text: bool, unique: bool,
}

#[rustfmt::skip]
fn strict_features(catalog: &ResolvedCatalogV1<'_>) -> StrictFeatures {
    let mut uses = StrictFeatures::default();
    for scalar in catalog.scalar_types() { match scalar.definition { ScalarDefinitionV1::SafeInteger { .. } => uses.integer = true, ScalarDefinitionV1::Text { .. } => { uses.string = true; uses.text = true; }, ScalarDefinitionV1::Code { .. } | ScalarDefinitionV1::TypedId { .. } => { uses.string = true; uses.pattern = true; }, ScalarDefinitionV1::Enum { .. } => uses.string = true } }
    uses.string |= !catalog.tagged_unions().is_empty();
    for field in catalog.records().iter().flat_map(|record| record.fields()) { match field.kind() {
        ResolvedFieldKindV1::LegacyValue => match strict_legacy_value(field.definition().field_type) { StrictLegacyValue::String(_) | StrictLegacyValue::OptionalString(_) => { uses.string = true; uses.pattern = true; uses.legacy_string = true; }, StrictLegacyValue::Schema | StrictLegacyValue::Enum(..) => uses.string = true, StrictLegacyValue::Uint | StrictLegacyValue::OptionalUint => uses.integer = true, StrictLegacyValue::Bool => uses.boolean = true, StrictLegacyValue::StringArray(_, maximum, unique) => { uses.arrays = true; uses.collect_array |= maximum == 0; uses.string = true; uses.pattern = true; uses.legacy_string = true; uses.bounds |= maximum != 0; uses.unique |= unique; }, StrictLegacyValue::EnumArray(..) => { uses.arrays = true; uses.collect_array = true; uses.string = true; }, StrictLegacyValue::OpenRefused | StrictLegacyValue::NotLegacyValue => {} },
        ResolvedFieldKindV1::LegacyReference { shape: LegacyReferenceShapeV1::Array, .. } => { uses.arrays = true; if field.definition().field_type == FieldTypeV1::ExecutionToolArray { uses.bounds = true; uses.unique = true; } else { uses.collect_array = true; } },
        ResolvedFieldKindV1::LegacyReference { .. } | ResolvedFieldKindV1::Named(_) | ResolvedFieldKindV1::OptionalNamed(_) => {},
        ResolvedFieldKindV1::BoundedArray { .. } => { uses.arrays = true; uses.bounds = true; uses.bounded_array = true; uses.rebase = true; },
        ResolvedFieldKindV1::BoundedSet { .. } => { uses.arrays = true; uses.bounds = true; uses.bounded_set = true; uses.rebase = true; uses.set = true; },
    } }
    uses
}

#[rustfmt::skip]
enum StrictLegacyValue {
    String(&'static str), Schema, Enum(&'static str, &'static str), Uint, OptionalUint,
    OptionalString(&'static str), Bool, StringArray(&'static str, usize, bool),
    EnumArray(&'static str, &'static str), OpenRefused, NotLegacyValue,
}

#[rustfmt::skip]
fn strict_legacy_value(field_type: FieldTypeV1) -> StrictLegacyValue {
    use FieldTypeV1::*;
    match field_type {
        String => StrictLegacyValue::String("nonempty"), SchemaVersion => StrictLegacyValue::Schema, PolicySchemaVersion => StrictLegacyValue::String("policy"), Identifier => StrictLegacyValue::String("identifier"), Digest => StrictLegacyValue::String("hex64"),
        OrganizationId => StrictLegacyValue::String("id:org"), RepositoryId => StrictLegacyValue::String("id:rep"), MissionId => StrictLegacyValue::String("id:mis"), AcceptanceContractId => StrictLegacyValue::String("id:acc"), PlanRevisionId => StrictLegacyValue::String("id:pln"), GraphRevisionId => StrictLegacyValue::String("id:grf"), WorkPackageId => StrictLegacyValue::String("id:wpk"), SelectionGroupId => StrictLegacyValue::String("id:sel"), VariantId => StrictLegacyValue::String("id:var"), AttemptId => StrictLegacyValue::String("id:atm"), RunnerId => StrictLegacyValue::String("id:run"), WorkspaceId => StrictLegacyValue::String("id:wsp"), PrincipalId => StrictLegacyValue::String("id:pri"), ProviderProfileId => StrictLegacyValue::String("id:prf"), ContentId => StrictLegacyValue::String("id:cnt"), MutationId => StrictLegacyValue::String("id:mut"), MutationReservationId => StrictLegacyValue::String("id:rsv"), ScopeGrantId => StrictLegacyValue::String("id:sgr"), SourceDescriptorId => StrictLegacyValue::String("id:src"), ChangeId => StrictLegacyValue::String("id:chg"), CheckpointId => StrictLegacyValue::String("id:ckp"), CandidateId => StrictLegacyValue::String("id:can"), GateReceiptId => StrictLegacyValue::String("id:grc"), ReleaseRegistryId => StrictLegacyValue::String("id:rrg"), GateId => StrictLegacyValue::String("id:gat"), EffectIntentId => StrictLegacyValue::String("id:efi"), CandidateProofRoot => StrictLegacyValue::String("id:cpr"), IntegrationProofRoot => StrictLegacyValue::String("id:ipr"),
        GitOid => StrictLegacyValue::String("git-oid"), TaggedBlake3Digest => StrictLegacyValue::String("blake3"), ReleaseGateId => StrictLegacyValue::String("release-gate"), ReleaseNativeSubjectId => StrictLegacyValue::String("native-subject"), ReleaseProfileId => StrictLegacyValue::String("profile"), ReleaseTag => StrictLegacyValue::String("release-tag"), SigningIdentity => StrictLegacyValue::String("signing"), SshEd25519PublicKey => StrictLegacyValue::String("ssh"), RepoPath => StrictLegacyValue::String("repo-path"), KeyId => StrictLegacyValue::String("key-id"), PasetoV4Public => StrictLegacyValue::String("paseto"),
        AuthorityAudience => StrictLegacyValue::Enum("AuthorityAudienceV1", "bullet-gitd effect-broker provider-runner"), MutationOperation => StrictLegacyValue::Enum("MutationOperationV1", "clone-workspace read-workspace apply-patch checkpoint prepare-candidate preserve-workspace cleanup-workspace dispatch-effect reconcile-effect"), AuthorityDecision => StrictLegacyValue::Enum("AuthorityDecisionV1", "authorized settled refused"), ReplayDisposition => StrictLegacyValue::Enum("ReplayDispositionV1", "fresh exact-replay conflict"), MutationResultState => StrictLegacyValue::Enum("MutationResultStateV1", "in-flight committed aborted unknown"), MutationOutcome => StrictLegacyValue::Enum("MutationOutcomeV1", "committed aborted unknown"), SettlementStatus => StrictLegacyValue::Enum("SettlementStatusV1", "accepted exact-replay conflict refused"), PatchPreimageKind => StrictLegacyValue::Enum("PatchPreimageKindV1", "absent digest"), PatchMutationKind => StrictLegacyValue::Enum("PatchMutationKindV1", "write delete"), ReleaseReceiptKind => StrictLegacyValue::Enum("ReleaseReceiptKindV1", "artifact containment forge operations profile-closure provider rust-toolchain scanner transaction"), ReleaseEvidenceKind => StrictLegacyValue::Enum("ReleaseEvidenceKindV1", "artifact audit-anchor candidate check configuration effect environment evidence integration jeryu observation platform policy profile-graph proof-bundle provider provenance sandbox sbom scanner schema toolchain transaction"), ReleaseRegistryObjectKind => StrictLegacyValue::Enum("ReleaseRegistryObjectKindV1", "gate-receipt gate-receipt-signature gate-spec profile-graph release-bundle-manifest-v2 signer-policy trusted-time-observation trusted-time-signature verification-request"), ReleaseSignerRole => StrictLegacyValue::Enum("ReleaseSignerRoleV1", "artifact-release gate-attestor registry-curator source-tag trusted-time"), ReleaseRepositoryName => StrictLegacyValue::Enum("ReleaseRepositoryNameV1", "bullet-farm bullet-git bullet-kernel bullet-portal"), KeyPurpose => StrictLegacyValue::Enum("KeyPurposeV1", "authority-signing release-signing"), KeyAlgorithm => StrictLegacyValue::Enum("KeyAlgorithmV1", "paseto-v4.public ssh-ed25519"),
        SafeU64 | U64 | Timestamp => StrictLegacyValue::Uint, OptionalTimestamp => StrictLegacyValue::OptionalUint, OptionalDigest => StrictLegacyValue::OptionalString("hex64"), OptionalString => StrictLegacyValue::OptionalString("any"), OptionalMutationReservationId => StrictLegacyValue::OptionalString("id:rsv"), Boolean => StrictLegacyValue::Bool,
        StringArray => StrictLegacyValue::StringArray("any", 0, false), CandidateIdArray => StrictLegacyValue::StringArray("id:can", 0, false), OrderedCandidateIdArray => StrictLegacyValue::StringArray("id:can", 128, true), GateIdArray => StrictLegacyValue::StringArray("id:gat", 0, false), ReleaseGateIdArray => StrictLegacyValue::StringArray("release-gate", 0, false), ReleaseProfileIdArray => StrictLegacyValue::StringArray("profile", 0, false), RepoPathArray => StrictLegacyValue::StringArray("repo-path", 0, false), AuthorityAudienceArray => StrictLegacyValue::EnumArray("AuthorityAudienceV1", "bullet-gitd effect-broker provider-runner"), ReleaseEvidenceKindArray => StrictLegacyValue::EnumArray("ReleaseEvidenceKindV1", "artifact audit-anchor candidate check configuration effect environment evidence integration jeryu observation platform policy profile-graph proof-bundle provider provenance sandbox sbom scanner schema toolchain transaction"),
        Object | ObjectArray => StrictLegacyValue::OpenRefused,
        IssuerKeyArray | RiskPolicy | EvidencePolicy | SandboxPolicy | BudgetPolicy | RoutePolicy | SignedAuthorityEnvelope | SignedMutationPermit | OptionalSignedMutationPermit | MutationReplayResult | OptionalMutationReplayResult | ScopeGrant | PatchProposal | PatchOperationArray | CleanupAuthorization | ReleaseFamilySubject | ReleaseRepositorySubjectArray | ReleaseEvidenceSubjectArray | ReleaseProfileNodeArray | ReleaseSignerKeyArray | ReleaseRegistryEntryArray | ReleaseRegistryObjectArray | ReleaseReplayBindingArray | ExecutionToolArray | NamedRef | OptionalNamedRef | BoundedArray | BoundedSet => StrictLegacyValue::NotLegacyValue,
    }
}

#[rustfmt::skip]
fn rust_strict_legacy_collect(field_type: FieldTypeV1) -> Result<String, WireError> {
    Ok(match strict_legacy_value(field_type) {
        StrictLegacyValue::String(rule) => format!("bullet_generated_legacy_string(value, path, \"{rule}\")?"),
        StrictLegacyValue::Schema => "match bullet_generated_string(value, path)?.as_str() { \"v1alpha1\" => SchemaVersionLiteralV1::V1alpha1, _ => return Err(bullet_generated_error(path)) }".into(),
        StrictLegacyValue::Enum(name, values) => rust_strict_enum_expression(name, values),
        StrictLegacyValue::Uint => "u64::try_from(bullet_generated_integer(value, path)?).map_err(|_| bullet_generated_error(path))?".into(),
        StrictLegacyValue::OptionalUint => "match value { BulletGeneratedUniqueJsonValueV1::Null => None, value => Some(u64::try_from(bullet_generated_integer(value, path)?).map_err(|_| bullet_generated_error(path))?) }".into(),
        StrictLegacyValue::OptionalString(rule) => format!("match value {{ BulletGeneratedUniqueJsonValueV1::Null => None, value => Some(bullet_generated_legacy_string(value, path, \"{rule}\")?) }}"),
        StrictLegacyValue::Bool => "bullet_generated_bool(value, path)?".into(),
        StrictLegacyValue::StringArray(rule, 0, false) => format!("bullet_generated_collect_array(value, path, |value, path| bullet_generated_legacy_string(value, path, \"{rule}\"))?"),
        StrictLegacyValue::StringArray(rule, maximum, unique) => format!("{{ let nodes = bullet_generated_array(value, path)?; bullet_generated_cardinality(nodes.len(), 0, {maximum}, path)?; let duplicate = {} let values = match bullet_generated_collect_nodes(nodes, path, |value, path| bullet_generated_legacy_string(value, path, \"{rule}\")) {{ Ok(values) => values, Err(error) => return Err(bullet_generated_choose(error, duplicate)) }}; if let Some(error) = duplicate {{ return Err(error); }} values }}", if unique { "bullet_generated_duplicate_failure(&nodes, path)?;" } else { "None;" }),
        StrictLegacyValue::EnumArray(name, values) => format!("bullet_generated_collect_array(value, path, |value, path| Ok({}))?", rust_strict_enum_expression(name, values)),
        StrictLegacyValue::OpenRefused | StrictLegacyValue::NotLegacyValue => return Err(impossible_field()),
    })
}

#[rustfmt::skip]
fn typescript_strict_legacy_collect(field_type: FieldTypeV1, value: &str, path: &str) -> Result<String, WireError> {
    Ok(match strict_legacy_value(field_type) {
        StrictLegacyValue::String(rule) => format!("bulletGeneratedLegacyString({value}, {path}, \"{rule}\")"), StrictLegacyValue::Schema => format!("bulletGeneratedString({value}, {path}) === \"v1alpha1\" ? \"v1alpha1\" : bulletGeneratedFail({path})"), StrictLegacyValue::Enum(_, values) => typescript_strict_enum_expression(values, value, path), StrictLegacyValue::Uint => format!("(() => {{ const item = bulletGeneratedInteger({value}, {path}); return item >= 0 ? item : bulletGeneratedFail({path}); }})()"), StrictLegacyValue::OptionalUint => format!("{value}.value === null ? null : (() => {{ const item = bulletGeneratedInteger({value}, {path}); return item >= 0 ? item : bulletGeneratedFail({path}); }})()"), StrictLegacyValue::OptionalString(rule) => format!("{value}.value === null ? null : bulletGeneratedLegacyString({value}, {path}, \"{rule}\")"), StrictLegacyValue::Bool => format!("bulletGeneratedBoolean({value}, {path})"),
        StrictLegacyValue::StringArray(rule, 0, false) => format!("bulletGeneratedCollectArray({value}, {path}, (item, itemPath) => bulletGeneratedLegacyString(item, itemPath, \"{rule}\"))"),
        StrictLegacyValue::StringArray(rule, maximum, unique) => { let duplicate = if unique { format!("bulletGeneratedDuplicateFailure(nodes, {path});") } else { "null;".into() }; format!("(() => {{ const nodes = bulletGeneratedArrayNode({value}, {path}); bulletGeneratedCardinality(nodes.length, 0, {maximum}, {path}); const duplicate = {duplicate} try {{ const values = bulletGeneratedCollectNodes(nodes, {path}, (item, itemPath) => bulletGeneratedLegacyString(item, itemPath, \"{rule}\")); if (duplicate !== null) bulletGeneratedFail(duplicate); return values; }} catch (error) {{ if (error instanceof BulletGeneratedFailure && duplicate !== null && bulletGeneratedCompareUtf8(duplicate, error.path) < 0) bulletGeneratedFail(duplicate); throw error; }} }})()") },
        StrictLegacyValue::EnumArray(_, values) => format!("bulletGeneratedCollectArray({value}, {path}, (item, itemPath) => {})", typescript_strict_enum_expression(values, "item", "itemPath")), StrictLegacyValue::OpenRefused | StrictLegacyValue::NotLegacyValue => return Err(impossible_field()),
    })
}

#[rustfmt::skip]
fn rust_strict_enum_expression(name: &str, values: &str) -> String {
    format!("{{ let item = bullet_generated_string(value, path)?; match item.as_str() {{ {} _ => return Err(bullet_generated_error(path)), }} }}", values.split_ascii_whitespace().map(|value| format!("\"{value}\" => {name}::{},", if value == "paseto-v4.public" { "PasetoV4Public".into() } else { rust_variant_identifier(value) })).collect::<String>())
}

#[rustfmt::skip]
fn typescript_strict_enum_expression(values: &str, value: &str, path: &str) -> String {
    format!("(() => {{ const item = bulletGeneratedString({value}, {path}); switch (item) {{ {} default: return bulletGeneratedFail({path}); }} }})()", values.split_ascii_whitespace().map(|item| format!("case \"{item}\": return item; ")).collect::<String>())
}
