use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
    process::{Command, Output},
    sync::atomic::{AtomicU64, Ordering},
};

static SEQUENCE: AtomicU64 = AtomicU64::new(0);

const LOCKED_PROFILES: &[&str] = &[
    "self-hosted-v1",
    "evolution-v1",
    "provider-claude",
    "provider-codex",
    "provider-cursor",
    "provider-antigravity",
    "jeryu-forge-v1",
    "github-adapter-v1",
    "gitlab-adapter-v1",
    "gitlab-self-managed-v1",
    "platform-linux-x86_64",
    "platform-linux-aarch64",
    "platform-macos-x86_64",
    "platform-macos-aarch64",
    "platform-windows-x86_64",
    "universal-v1",
    "team-v1",
    "saga-v1",
];

struct Registry(PathBuf);

impl Registry {
    fn new() -> Self {
        let sequence = SEQUENCE.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "bullet-release-profiles-{}-{sequence}",
            std::process::id()
        ));
        if path.exists() {
            fs::remove_dir_all(&path).unwrap();
        }
        fs::create_dir(&path).unwrap();
        Self(path)
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for Registry {
    fn drop(&mut self) {
        fs::remove_dir_all(&self.0).unwrap();
    }
}

fn command(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_bullet-family"))
        .args(args)
        .current_dir(env!("CARGO_MANIFEST_DIR"))
        .output()
        .expect("run bullet-family")
}

fn report(profile: &str, registry: &Path) -> serde_json::Value {
    let output = command(&[
        "check",
        "release",
        "--profile",
        profile,
        "--receipts",
        registry.to_str().unwrap(),
        "--json",
    ]);
    assert_eq!(output.status.code(), Some(3), "profile={profile}");
    assert!(output.stderr.is_empty(), "profile={profile}");
    let report: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(report["profile"], profile);
    assert_eq!(report["status"], "BLOCKED");
    assert!(report["gates"].as_array().unwrap().iter().all(|gate| {
        gate["status"] == "BLOCKED"
            && gate["repair"]
                .as_str()
                .is_some_and(|repair| !repair.is_empty())
    }));
    report
}

fn ids(report: &serde_json::Value) -> BTreeSet<String> {
    report["gates"]
        .as_array()
        .unwrap()
        .iter()
        .map(|gate| gate["id"].as_str().unwrap().to_owned())
        .collect()
}

#[test]
fn ordinary_release_requires_an_explicit_profile() {
    for args in [vec!["check", "release"], vec!["check", "release", "--json"]] {
        let output = command(&args);
        assert_eq!(output.status.code(), Some(2));
        assert!(output.stdout.is_empty());
        let error = String::from_utf8(output.stderr).unwrap();
        assert!(error.contains("PROFILE_REQUIRED"));
        assert!(error.contains("legacy-v1-26 is diagnostic only"));
    }

    for args in [
        vec!["check", "release", "--report"],
        vec!["check", "release", "--report", "--portable"],
    ] {
        let output = command(&args);
        assert_eq!(output.status.code(), Some(2));
        assert!(output.stdout.is_empty());
        assert!(
            String::from_utf8(output.stderr)
                .unwrap()
                .contains("PROFILE_REQUIRED")
        );
    }

    let unprofiled_registry = Registry::new();
    let output = command(&[
        "check",
        "release",
        "--receipts",
        unprofiled_registry.path().to_str().unwrap(),
        "--json",
    ]);
    assert_eq!(output.status.code(), Some(2));
    assert!(output.stdout.is_empty());
    assert!(
        String::from_utf8(output.stderr)
            .unwrap()
            .contains("PROFILE_REQUIRED")
    );

    let registry = Registry::new();
    let output = command(&[
        "check",
        "release",
        "--profile",
        "legacy-v1-26",
        "--receipts",
        registry.path().to_str().unwrap(),
        "--report",
        "--portable",
    ]);
    assert_eq!(output.status.code(), Some(3));
    assert!(output.stderr.is_empty());
    assert!(
        output
            .stdout
            .starts_with(b"<!-- Generated by: bullet-family check release --profile legacy-v1-26")
    );
}

#[test]
fn every_locked_profile_is_named_and_fail_closed() {
    let registry = Registry::new();
    for profile in LOCKED_PROFILES {
        report(profile, registry.path());
    }
}

#[test]
fn dependencies_compose_without_smuggling_evolution_into_universal() {
    let registry = Registry::new();
    let self_hosted = ids(&report("self-hosted-v1", registry.path()));
    let expected_self_hosted = [
        "release.backup-restore",
        "release.checksums",
        "release.fault-suite",
        "release.forge.jeryu",
        "release.installable-lock",
        "release.installer-twice",
        "release.jankurai-90",
        "release.manifest-non-circular",
        "release.package-linux-x86_64",
        "release.platform-containment",
        "release.profile.jeryu-forge-v1",
        "release.profile.platform-linux-x86_64",
        "release.profile.provider-claude",
        "release.profile.self-hosted-v1",
        "release.provenance",
        "release.provider.claude",
        "release.receipt-contracts",
        "release.rust-msrv-1-95",
        "release.rust-pinned-1-97-1",
        "release.scan.dependency",
        "release.scan.license",
        "release.scan.secret",
        "release.scan.workflow",
        "release.sbom",
        "release.signatures",
        "release.systemd-v1",
        "release.transaction-demo",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect::<BTreeSet<_>>();
    assert_eq!(self_hosted, expected_self_hosted);
    for required in [
        "release.profile.self-hosted-v1",
        "release.profile.provider-claude",
        "release.profile.jeryu-forge-v1",
        "release.profile.platform-linux-x86_64",
    ] {
        assert!(self_hosted.contains(required), "missing {required}");
    }
    assert!(!self_hosted.contains("release.profile.evolution-v1"));
    for independent in [
        "release.package-matrix",
        "release.profile.provider-codex",
        "release.profile.provider-cursor",
        "release.profile.provider-antigravity",
        "release.profile.github-adapter-v1",
        "release.profile.gitlab-adapter-v1",
        "release.profile.gitlab-self-managed-v1",
        "release.profile.platform-linux-aarch64",
        "release.profile.platform-macos-x86_64",
        "release.profile.platform-macos-aarch64",
        "release.profile.platform-windows-x86_64",
    ] {
        assert!(
            !self_hosted.contains(independent),
            "self-hosted smuggled independent subject {independent}"
        );
    }
    assert!(self_hosted.contains("release.package-linux-x86_64"));
    assert!(self_hosted.contains("release.platform-containment"));

    let jeryu_report = report("jeryu-forge-v1", registry.path());
    assert_eq!(
        ids(&jeryu_report),
        [
            "release.forge.jeryu",
            "release.profile.jeryu-forge-v1",
            "release.receipt-contracts",
        ]
        .into_iter()
        .map(str::to_owned)
        .collect::<BTreeSet<_>>()
    );
    assert!(!ids(&jeryu_report).contains("release.backup-restore"));
    let jeryu_condition = jeryu_report["gates"]
        .as_array()
        .unwrap()
        .iter()
        .find(|gate| gate["id"] == "release.profile.jeryu-forge-v1")
        .unwrap();
    assert!(
        jeryu_condition["detail"]
            .as_str()
            .unwrap()
            .contains("reconciliation, backup/restore, and drift refusal")
    );

    let evolution = ids(&report("evolution-v1", registry.path()));
    assert!(self_hosted.is_subset(&evolution));
    assert!(evolution.contains("release.profile.evolution-v1"));

    let universal_report = report("universal-v1", registry.path());
    let universal = ids(&universal_report);
    for required in [
        "release.profile.self-hosted-v1",
        "release.profile.provider-claude",
        "release.profile.provider-codex",
        "release.profile.provider-cursor",
        "release.profile.provider-antigravity",
        "release.profile.jeryu-forge-v1",
        "release.profile.github-adapter-v1",
        "release.profile.gitlab-adapter-v1",
        "release.profile.gitlab-self-managed-v1",
        "release.profile.platform-linux-x86_64",
        "release.profile.platform-linux-aarch64",
        "release.profile.platform-macos-x86_64",
        "release.profile.platform-macos-aarch64",
        "release.profile.platform-windows-x86_64",
        "release.profile.universal-v1",
    ] {
        assert!(universal.contains(required), "missing {required}");
    }
    for excluded in [
        "release.profile.evolution-v1",
        "release.profile.team-v1",
        "release.profile.saga-v1",
    ] {
        assert!(!universal.contains(excluded), "leaked {excluded}");
    }
    for native in ["release.package-linux-x86_64", "release.systemd-v1"] {
        assert!(universal.contains(native), "missing {native}");
        assert_eq!(
            universal_report["gates"]
                .as_array()
                .unwrap()
                .iter()
                .filter(|gate| gate["id"] == native)
                .count(),
            1,
            "duplicated {native}",
        );
    }
    for preview_only in ["release.evolution-v1", "release.operations-v1"] {
        assert!(!universal.contains(preview_only), "leaked {preview_only}");
    }

    let saga = ids(&report("saga-v1", registry.path()));
    for required in [
        "release.profile.self-hosted-v1",
        "release.profile.team-v1",
        "release.profile.saga-v1",
    ] {
        assert!(saga.contains(required), "missing {required}");
    }
    assert!(!saga.contains("release.profile.evolution-v1"));
}

#[test]
fn legacy_is_exactly_the_old_26_gate_diagnostic() {
    let registry = Registry::new();
    let report = report("legacy-v1-26", registry.path());
    let ids = ids(&report);
    assert_eq!(ids.len(), 26);
    assert!(!ids.iter().any(|id| id.starts_with("release.profile.")));
    for required in [
        "release.provider.claude",
        "release.provider.codex",
        "release.provider.cursor",
        "release.provider.antigravity",
        "release.forge.jeryu",
        "release.forge.github-app",
        "release.package-matrix",
    ] {
        assert!(ids.contains(required));
    }
}

#[test]
fn a_regular_file_registry_is_failure_never_evidence() {
    let sequence = SEQUENCE.fetch_add(1, Ordering::Relaxed);
    let path = std::env::temp_dir().join(format!(
        "bullet-release-profile-file-{}-{sequence}",
        std::process::id()
    ));
    fs::write(&path, b"not a registry").unwrap();
    let output = command(&[
        "check",
        "release",
        "--profile",
        "provider-codex",
        "--receipts",
        path.to_str().unwrap(),
        "--json",
    ]);
    assert_eq!(output.status.code(), Some(1));
    let report: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    let gates = report["gates"].as_array().unwrap();
    assert!(gates.iter().all(|gate| gate["status"] != "PASS"));
    let receipt = gates
        .iter()
        .find(|gate| gate["id"] == "release.receipt-contracts")
        .unwrap();
    assert_eq!(receipt["status"], "FAIL");
    fs::remove_file(path).unwrap();
}
