//! Deterministic Markdown rendering of the release truth page.

use std::fmt::Write as _;

use super::{
    facts::{Facts, Mechanical, Register, Variant},
    rows::{self, ClaimRow, UngatedRow},
};
use crate::{
    check::{
        model::{CheckReport, GateResult, GateStatus},
        profiles::ReleaseProfile,
    },
    coord::CoordError,
};

const PROJECTION: &str =
    "PROJECTION — rendered from machine facts; this page holds no release authority";
pub(super) const UNGATED_HEADING: &str = "## Blocking but not a release gate";
pub(super) const CROSSWALK_HEADING: &str = "## Product-gap crosswalk";

pub(super) fn render(facts: &Facts, report: &CheckReport) -> Result<String, CoordError> {
    let mut out = String::new();
    header(&mut out, facts, report);
    subjects(&mut out, facts);
    lock(&mut out, facts);
    truths(&mut out, facts, report);
    gates(&mut out, report)?;
    crosswalk(&mut out, facts, report);
    ungated(&mut out, report)?;
    excluded(&mut out);
    freshness(&mut out, facts, report);
    while out.ends_with('\n') {
        out.pop();
    }
    Ok(out)
}

fn header(out: &mut String, facts: &Facts, report: &CheckReport) {
    let profile = report.profile().unwrap_or("PROFILE_REQUIRED");
    let (variant, variant_note) = match facts.variant {
        Variant::Live => (
            "--report",
            "LIVE — machine-local subjects, absolute paths, and mtimes are included",
        ),
        Variant::Portable => (
            "--report --portable",
            "PORTABLE — machine-local subjects, absolute paths, and mtimes are excluded; reproducible from a fresh hub-only checkout",
        ),
    };
    let command = if facts.variant == Variant::Portable && profile == "universal-v1" {
        "just release-truth".to_owned()
    } else {
        format!(
            "bullet-family check release --profile {profile} --receipts ABSOLUTE_REGISTRY {variant}"
        )
    };
    let _ = writeln!(
        out,
        "<!-- Generated by: bullet-family check release --profile {profile} --receipts ABSOLUTE_REGISTRY {variant} -->\n<!-- Source: src/check/prerequisites.rs + src/check/truth/rows.rs + family.lock + repos.manifest.toml + docs/release.md + docs/assurance/product-gaps.md -->\n<!-- Command: {command} -->\n<!-- DO NOT EDIT BY HAND. -->\n\n# Release truth\n\nRELEASE DECISION: {}\n",
        report.status().as_str()
    );
    let head = facts.hub_head_committed_at.as_deref().map_or_else(
        || "hub HEAD committer date not read".to_owned(),
        |date| format!("hub HEAD committed {date} (source: git log -1 --format=%cI)"),
    );
    let reviewed = facts.release_index.last_reviewed.as_deref().map_or_else(
        || {
            format!(
                "`{}` has no `Last reviewed:` line",
                super::facts::RELEASE_INDEX
            )
        },
        |date| format!("`{}` Last reviewed: {date}", super::facts::RELEASE_INDEX),
    );
    let _ = writeln!(out, "| Field | Value |\n| --- | --- |");
    let _ = writeln!(
        out,
        "| as_of | {head}; {reviewed}; no wall clock was read |"
    );
    let _ = writeln!(
        out,
        "| source | `bullet-family {}` static release inventory, check report schema {}, tier {}, {} gates |",
        env!("CARGO_PKG_VERSION"),
        report.schema_version(),
        report.tier().as_str(),
        report.gates().len()
    );
    let inventory_scope = if profile == "legacy-v1-26" {
        "is this static diagnostic inventory; its syntactically required registry argument is not evaluated"
    } else {
        "combines this exact profile inventory with its selected semantic-admission machinery"
    };
    let _ = writeln!(
        out,
        "| scope | the {} registered release gates of the four-repository Bullet Farm family, each mapped to its product gap G-id from `{}`; gap {} {inventory_scope}; nothing outside the catalog is counted |",
        report.gates().len(),
        super::facts::PRODUCT_GAP_REGISTER,
        rows::INVENTORY_GAP
    );
    let _ = writeln!(
        out,
        "| freshness | every projected input is identified in the Freshness section; receipt-registry path and identity are excluded and this projection is not evidence; a gate row changes only when its catalog entry, claim row, register crosswalk, or evaluation outcome changes |"
    );
    let _ = writeln!(out, "| projection | {PROJECTION} |");
    let _ = writeln!(out, "| variant | {variant_note} |");
    let required_closure = report
        .profile()
        .and_then(|name| ReleaseProfile::parse(name).ok())
        .map(ReleaseProfile::required_closure)
        .unwrap_or("an explicit release profile before admission can be evaluated");
    let _ = writeln!(out, "| profile | `{profile}` |");
    let _ = writeln!(out, "| required closure | {required_closure} |");
    let receipt_source = match report.profile() {
        Some("legacy-v1-26") => {
            "diagnostic-only: `--receipts` is syntactically required but its contents are deliberately ignored; no registry or legacy fixed `/etc` descriptor is read"
        }
        Some(_) if facts.variant == Variant::Portable => {
            "the selected semantic registry was evaluated before rendering, but this portable projection excludes its path and identity and is not evidence; the legacy fixed `/etc/bullet-farm/release-msrv-1-95-admission.toml` descriptor is deliberately not read"
        }
        Some(_) => {
            "the selected semantic registry was evaluated, but this projection does not bind its path or identity and is not evidence; the legacy fixed `/etc/bullet-farm/release-msrv-1-95-admission.toml` descriptor is deliberately not read"
        }
        None => "no selected semantic registry because no explicit profile was supplied",
    };
    let _ = writeln!(out, "| receipt admission | {receipt_source} |");
    if let Some(hub) = &facts.hub_root {
        let _ = writeln!(out, "| hub | `{hub}` |");
    }
    out.push('\n');
}

fn subjects(out: &mut String, facts: &Facts) {
    let _ = writeln!(
        out,
        "## Repository subjects\n\n| Repository | Commit | Tree | Checkout |\n| --- | --- | --- | --- |"
    );
    for subject in &facts.subjects {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            subject.name,
            code_or_unknown(subject.commit.as_deref()),
            code_or_unknown(subject.tree.as_deref()),
            subject.checkout
        );
    }
    out.push('\n');
}

fn lock(out: &mut String, facts: &Facts) {
    let _ = writeln!(out, "## Family lock\n\n| Field | Value |\n| --- | --- |");
    match &facts.lock {
        Err(error) => {
            let _ = writeln!(out, "| schema | UNKNOWN ({error}) |\n| tag | UNKNOWN |");
            let _ = writeln!(out, "| binds current HEADs | UNKNOWN (lock unreadable) |");
        }
        Ok(lock) => {
            let install = if lock.installable {
                "strict schema-3 lock; install authority still requires signed subjects"
            } else {
                "diagnostic-only; every installer path refuses it by design"
            };
            let _ = writeln!(out, "| schema | {} ({install}) |", lock.schema_version);
            let _ = writeln!(out, "| tag | `{}` |", lock.tag);
            let _ = writeln!(out, "| binds current HEADs | {} |", binding(facts, lock));
        }
    }
    out.push('\n');
}

fn binding(facts: &Facts, lock: &crate::doctor::LockSummary) -> String {
    if facts.variant == Variant::Portable {
        return "UNKNOWN (portable variant does not read checkouts)".to_owned();
    }
    let mut mismatches = Vec::new();
    for (name, locked) in &lock.members {
        let live = facts
            .subjects
            .iter()
            .find(|subject| subject.name == name)
            .and_then(|subject| subject.commit.as_deref());
        match live {
            Some(commit) if commit.split_once(':').map(|pair| pair.1) == Some(locked) => {}
            Some(commit) => mismatches.push(format!("{name} locked `{locked}` HEAD `{commit}`")),
            None => mismatches.push(format!("{name} locked `{locked}` HEAD UNKNOWN")),
        }
    }
    if mismatches.is_empty() {
        "YES — every locked member commit equals its current HEAD".to_owned()
    } else {
        format!("NO — {}", mismatches.join("; "))
    }
}

fn receipted(report: &CheckReport) -> usize {
    report
        .gates()
        .iter()
        .filter(|gate| gate.status() == GateStatus::Pass)
        .count()
}

fn truths(out: &mut String, facts: &Facts, report: &CheckReport) {
    let receipted = receipted(report);
    let total = report.gates().len();
    let _ = writeln!(
        out,
        "## Five truths, never conflated\n\n| Truth | Status | Source | Scope |\n| --- | --- | --- | --- |"
    );
    for fact in &facts.mechanical {
        let status = match &fact.outcome {
            Mechanical::NotRead => {
                "NOT RUN (portable variant does not read machine-local check reports)".to_owned()
            }
            Mechanical::Absent => "NOT RUN (no generated check report)".to_owned(),
            Mechanical::Unreadable(reason) => format!("NOT RUN (unreadable: {reason})"),
            Mechanical::Stale {
                status,
                gates,
                mismatch,
            } => {
                format!(
                    "STALE — {status} over {gates} gates recorded against other subjects ({mismatch})"
                )
            }
            Mechanical::Fresh { status, gates } => {
                format!("{status} — {gates} gates on current HEADs")
            }
        };
        let _ = writeln!(
            out,
            "| Mechanical gates ({}) | {status} | `{}` written by `bullet-family check {} --json` | fixed {} command catalog; a pass here is not release readiness |",
            fact.tier, fact.path, fact.tier, fact.tier
        );
    }
    let evidence_source = match report.profile() {
        Some("legacy-v1-26") => {
            "static diagnostic inventory; the syntactically required `--receipts` argument is ignored and cannot change any gate"
        }
        Some(_) => {
            "the selected semantic registry is read for this exact profile; its identity is excluded from this projection, the legacy fixed `/etc/bullet-farm/release-msrv-1-95-admission.toml` descriptor is deliberately not read, and structural validity cannot make a gate PASS"
        }
        None => {
            "static negative inventory in `src/check/prerequisites.rs`; the legacy unprofiled MSRV evaluator is not a public release-admission path"
        }
    };
    let _ = writeln!(
        out,
        "| Evidence completeness | {receipted} of {total} receipted | {evidence_source} | the {total} registered release gates |"
    );
    let review = if receipted == total {
        "OPEN — every gate is receipted; human release review may begin"
    } else {
        "HOLD — no receipt exists to review"
    };
    let _ = writeln!(
        out,
        "| Release review | {review} | this page; no reviewer record exists | human verification of receipted gates |"
    );
    let _ = writeln!(
        out,
        "| Deployment match | N/A — pre-release; nothing is deployed | no deployment record exists | deployed SHA versus reviewed integration subject |"
    );
    let _ = writeln!(
        out,
        "| Post-deploy survival | NOT ESTABLISHED | no deployment observation exists | required observations after a deployment |"
    );
    out.push('\n');
}

fn gates(out: &mut String, report: &CheckReport) -> Result<(), CoordError> {
    let unproved = report.gates().len() - receipted(report);
    let _ = writeln!(
        out,
        "## Gates ({unproved} of {} unproved)\n",
        report.gates().len()
    );
    for (index, gate) in report.gates().iter().enumerate() {
        let row = rows::find(gate.id()).ok_or_else(|| {
            CoordError::new(
                "RELEASE_TRUTH_ROW_MISSING",
                format!("no claim row for gate {}", gate.id()),
            )
        })?;
        gate_row(out, index + 1, gate, row, report.profile())?;
    }
    Ok(())
}

fn reads_closed(id: &str, texts: &[&str]) -> Result<(), CoordError> {
    if texts.iter().any(|text| rows::contains_closed_word(text)) {
        return Err(CoordError::new(
            "RELEASE_TRUTH_CLAIM_READS_CLOSED",
            format!(
                "{id} is unreceipted but its row uses one of {:?}",
                rows::CLOSED_WORDS
            ),
        ));
    }
    Ok(())
}

fn gate_row(
    out: &mut String,
    number: usize,
    gate: &GateResult,
    row: &ClaimRow,
    profile: Option<&str>,
) -> Result<(), CoordError> {
    let receipted = gate.status() == GateStatus::Pass;
    let legacy_static = profile == Some("legacy-v1-26")
        && matches!(
            gate.id(),
            "release.receipt-contracts" | "release.rust-msrv-1-95"
        );
    let (legacy_headline, why, acceptance, exists, owner) = match gate.id() {
        "release.receipt-contracts" if legacy_static => (
            "The historical receipt-contract row is selected statically; this diagnostic does not evaluate or admit registry contents.",
            "The historical catalog is retained for comparison only and has no signer, time, replay, or semantic admission authority.",
            "NONE for `legacy-v1-26` — choose a conformant semantic release profile; this diagnostic cannot close or waive G12.",
            "the semantic registry verifier used by conformant profiles; `legacy-v1-26` deliberately does not call it",
            "LOCAL (diagnostic maintenance only) — preserve the row as non-admitting historical inventory",
        ),
        "release.rust-msrv-1-95" if legacy_static => (
            "The historical Rust 1.95 row is static; this diagnostic does not evaluate a build receipt.",
            row.why,
            "NONE for `legacy-v1-26` — choose a conformant semantic release profile; this diagnostic cannot admit an MSRV receipt.",
            "the Rust 1.95 component lane and the semantic verifier used by conformant profiles; neither is evaluated as evidence by `legacy-v1-26`",
            "LOCAL (diagnostic maintenance only) — preserve the row as non-admitting historical inventory",
        ),
        _ => (row.claim, row.why, row.acceptance, row.exists, ""),
    };
    let owner = if legacy_static {
        owner.to_owned()
    } else {
        row.owner.render()
    };
    let headline = if receipted {
        format!("Receipted: {}", gate.detail())
    } else if rows::is_condition(gate.id()) {
        gate.detail().to_owned()
    } else if legacy_static {
        legacy_headline.to_owned()
    } else {
        row.claim.to_owned()
    };
    if !receipted {
        if legacy_static {
            reads_closed(
                gate.id(),
                &[headline.as_str(), why, acceptance, exists, owner.as_str()],
            )?;
        } else {
            reads_closed(gate.id(), &row.texts())?;
        }
    }
    let _ = writeln!(
        out,
        "{number}. **{headline}** — `{}` {}",
        gate.id(),
        gate.status().as_str()
    );
    let _ = writeln!(out, "   - Product gap: {}", row.gap_ids.join(", "));
    let _ = writeln!(out, "   - Why it matters: {why}");
    let _ = writeln!(out, "   - Acceptance: {acceptance}");
    let _ = writeln!(out, "   - Evidence class: {}_PROOF", gate.class().as_str());
    let evidence = match gate.status() {
        GateStatus::Pass => gate.detail().to_owned(),
        GateStatus::Fail => format!(
            "REJECTED — {}; exists but does not count: {}",
            gate.detail(),
            exists
        ),
        _ => format!(
            "NONE — {}; exists but does not count: {}",
            gate.detail(),
            exists
        ),
    };
    let _ = writeln!(out, "   - Current evidence: {evidence}");
    let _ = writeln!(out, "   - Owner: {owner}");
    let _ = writeln!(
        out,
        "   - Next command: {}",
        next_command(gate, row, profile)
    );
    let _ = writeln!(out, "   - Release-blocking: yes");
    Ok(())
}

fn next_command(gate: &GateResult, row: &ClaimRow, profile: Option<&str>) -> String {
    let Some(profile) = profile else {
        return row.next.render();
    };
    if profile == "legacy-v1-26" {
        return row.next.render();
    }
    if rows::is_condition(gate.id()) {
        return format!(
            "`bullet-family check release --profile {profile} --receipts /absolute/admitted-registry --json` — reports this exact selected profile against its registry; structural or absent input cannot clear it"
        );
    }
    if gate.id() == "release.receipt-contracts" {
        return format!(
            "`bullet-family check release --profile {profile} --receipts /absolute/admitted-registry --json` — evaluates generic signer, trusted-time, replay, exact-family, and semantic admission for this exact selected profile"
        );
    }
    if gate.id() == "release.rust-msrv-1-95" {
        return format!(
            "`bullet-family check release --profile {profile} --receipts /absolute/admitted-registry --json` — reads the selected semantic registry and deliberately does not read the legacy fixed `/etc/bullet-farm/release-msrv-1-95-admission.toml` descriptor"
        );
    }
    row.next.render()
}

fn crosswalk(out: &mut String, facts: &Facts, report: &CheckReport) {
    let inventory_explanation = if report.profile() == Some("legacy-v1-26") {
        "For the legacy diagnostic G12 is inventory-only: `release.receipt-contracts` remains a static catalog row and no semantic registry is evaluated."
    } else {
        "For semantic profiles G12 deliberately shows both the inventory projection and its semantic-admission gate without counting either as evidence."
    };
    let _ = writeln!(
        out,
        "\n{CROSSWALK_HEADING}\n\nEvery G-id of `{}` is visible here: by selected gate rows, by the ungated section below, or by this exact profile inventory. {inventory_explanation} Titles are compiled; the crosswalk rows are read from the register and compared here.\n\n| Gap | Title | Answered by |\n| --- | --- | --- |",
        super::facts::PRODUCT_GAP_REGISTER,
    );
    let profile = report.profile().unwrap_or("unprofiled");
    for &(gap, title) in rows::PRODUCT_GAPS {
        let global_gates = rows::gates_for(gap);
        let gates = global_gates
            .iter()
            .copied()
            .filter(|id| report.gates().iter().any(|gate| gate.id() == *id))
            .collect::<Vec<_>>();
        let answer = if gap == rows::INVENTORY_GAP {
            let admission = if profile == "legacy-v1-26" {
                "diagnostic `release.receipt-contracts` row selected statically; `--receipts` contents ignored"
                    .to_owned()
            } else if gates.is_empty() {
                "semantic admission gate not selected".to_owned()
            } else {
                format!(
                    "semantic admission: {}; the requested profile-condition receipt must also pass, and neither half can substitute for the other",
                    gates
                        .iter()
                        .map(|id| format!("`{id}`"))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            };
            format!(
                "this `{profile}` inventory — {} selected gates, {} receipted; {admission} (historical diagnostic: `bullet-family check release --profile legacy-v1-26 --receipts ABSOLUTE_REGISTRY --report --portable`)",
                report.gates().len(),
                receipted(report)
            )
        } else if !gates.is_empty() {
            gates
                .iter()
                .map(|id| format!("`{id}`"))
                .collect::<Vec<_>>()
                .join(", ")
        } else if !global_gates.is_empty() {
            format!(
                "NOT SELECTED BY `{profile}` — independently owned by {}",
                global_gates
                    .iter()
                    .map(|id| format!("`{id}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        } else if rows::ungated_for(gap).is_some() {
            if gap == "G4"
                && !report
                    .gates()
                    .iter()
                    .any(|gate| gate.id() == "release.transaction-demo")
            {
                "ungated — not release-blocking for this profile because `release.transaction-demo` is not selected; see below".to_owned()
            } else {
                "ungated — release-blocking through the selected `release.transaction-demo`; see below".to_owned()
            }
        } else {
            "UNANSWERED".to_owned()
        };
        let _ = writeln!(out, "| {gap} | {title} | {answer} |");
    }
    let _ = writeln!(
        out,
        "\nAgreement with `{}`: {}",
        super::facts::PRODUCT_GAP_REGISTER,
        agreement(&facts.register)
    );
}

fn agreement(register: &Register) -> String {
    let table = match register {
        Register::Absent => {
            return "UNKNOWN — the register is absent from this checkout".to_owned();
        }
        Register::Unparsed(reason) => return format!("UNKNOWN — register unparsed: {reason}"),
        Register::Read(table) => table,
    };
    let diffs = rows::crosswalk_diffs(table);
    if diffs.is_empty() {
        format!(
            "YES — all {} crosswalk rows and the G-id list agree",
            table.gates.len()
        )
    } else {
        format!("NO — {}", diffs.join("; "))
    }
}

fn ungated(out: &mut String, report: &CheckReport) -> Result<(), CoordError> {
    let _ = writeln!(
        out,
        "\n{UNGATED_HEADING}\n\nProduct gaps with no `release.*` id. Each row says which gate it blocks through; none can be receipted here, and each is listed so that no G-id is invisible to machine output.\n"
    );
    for (index, row) in rows::UNGATED.iter().enumerate() {
        ungated_row(out, index + 1, row, report)?;
    }
    Ok(())
}

fn ungated_row(
    out: &mut String,
    number: usize,
    row: &UngatedRow,
    report: &CheckReport,
) -> Result<(), CoordError> {
    reads_closed(row.gap_id, &row.texts())?;
    let title = rows::gap_title(row.gap_id).unwrap_or("UNKNOWN GAP");
    let _ = writeln!(out, "{number}. **{}** — {} {title}", row.claim, row.gap_id);
    let _ = writeln!(out, "   - Why it matters: {}", row.why);
    let _ = writeln!(out, "   - Acceptance: {}", row.acceptance);
    let _ = writeln!(out, "   - Evidence class: {}_PROOF", row.class.as_str());
    let _ = writeln!(out, "   - Current evidence: {}", row.evidence);
    let _ = writeln!(out, "   - Owner: {}", row.owner.render());
    let _ = writeln!(out, "   - Next command: {}", row.next.render());
    let blocking = if row.gap_id == "G4"
        && !report
            .gates()
            .iter()
            .any(|gate| gate.id() == "release.transaction-demo")
    {
        "no for this profile — `release.transaction-demo` is not selected"
    } else {
        row.blocking
    };
    let _ = writeln!(out, "   - Release-blocking: {blocking}");
    Ok(())
}

fn excluded(out: &mut String) {
    let _ = writeln!(
        out,
        "\n## Excluded from this decision\n\n\
- Self-signed component receipts, including the `required.demo-component` simulator lane: COMPONENT_PROOF never counts toward a transaction, live, or release gate.\n\
- Simulator runs, fixture-only policies, and the fixture-only live-enabled v1alpha2 policy: none is an operator ratification.\n\
- Prose: `docs/release.md`, `docs/assurance/product-gaps.md`, `docs/assurance/v1-closure-plan.md`, ADRs, changelog, and coordination chat describe evidence; they are not evidence.\n\
- Component receipts named in `docs/release.md` and in the “exists but does not count” text above: COMPONENT_PROOF for one crate or surface, never transaction, live, or release evidence.\n\
- The archived 2026-08-24 live demonstration receipt at the family root `.l7-bundle/`: incident evidence only (`transaction_gate_eligible: false`); it is not counted.\n\
- Any mechanical gate result recorded against subjects other than the current HEADs (STALE above).\n\
- Reviewer checkmarks, browser-local marks, exit codes, model statements, pushed branches, and pull requests."
    );
}

fn freshness(out: &mut String, facts: &Facts, report: &CheckReport) {
    let _ = writeln!(
        out,
        "\n## Freshness\n\n| Input | Path | Identity | mtime (unix seconds) |\n| --- | --- | --- | --- |"
    );
    for input in &facts.inputs {
        let mtime = match (&input.mtime, facts.variant) {
            (Some(mtime), _) => mtime.clone(),
            (None, Variant::Portable) => "excluded (portable variant)".to_owned(),
            (None, Variant::Live) => "—".to_owned(),
        };
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | {mtime} |",
            input.label, input.path, input.identity
        );
    }
    let _ = writeln!(
        out,
        "| gate catalog | `src/check/prerequisites.rs` (compiled into `bullet-family {}`) | check report schema {} | — |",
        env!("CARGO_PKG_VERSION"),
        report.schema_version()
    );
    let _ = writeln!(
        out,
        "| claim rows | `src/check/truth/rows.rs` + `rows/gates.rs` + `rows/ungated.rs` (compiled into `bullet-family {}`) | {} gate rows + {} ungated rows over {} G-ids | — |",
        env!("CARGO_PKG_VERSION"),
        rows::row_count(),
        rows::UNGATED.len(),
        rows::PRODUCT_GAPS.len()
    );
}

fn code_or_unknown(value: Option<&str>) -> String {
    value.map_or_else(|| "UNKNOWN".to_owned(), |value| format!("`{value}`"))
}
