//! Rust data models and offline JSON Schema from the same authored OpenAPI.

use serde_yaml::{Mapping, Value};
use std::collections::BTreeSet;
use std::fmt::Write;

pub(super) fn artifacts() -> Result<Vec<(&'static str, String)>, String> {
    let text = std::fs::read_to_string(super::repo_root().join("contracts/openapi.yaml"))
        .map_err(|_| "read OpenAPI for Rust generation")?;
    let document: Value =
        serde_yaml::from_str(&text).map_err(|_| "parse OpenAPI for Rust generation")?;
    let schemas = document
        .get("components")
        .and_then(|v| v.get("schemas"))
        .and_then(Value::as_mapping)
        .ok_or("OpenAPI schemas absent")?;
    let mut definitions = serde_json::to_value(schemas).map_err(|_| "encode API schemas")?;
    super::rewrite_component_refs(&mut definitions)?;
    let schema = serde_json::json!({"$schema": "https://json-schema.org/draft/2020-12/schema", "$defs": definitions});
    Ok(vec![
        ("api.rs", models(schemas)?),
        (
            "api.schema.json",
            format!(
                "{}\n",
                serde_json::to_string_pretty(&schema).map_err(|_| "encode schema bundle")?
            ),
        ),
    ])
}

fn models(schemas: &Mapping) -> Result<String, String> {
    let mut out = String::from("// Generated by bullet contracts generate from contracts/openapi.yaml. Do not edit.\n// All schema constraints are checked before deserialization by the CLI client.\n#![allow(dead_code)]\n\npub trait ApiModel: serde::de::DeserializeOwned {\n    const SCHEMA_NAME: &'static str;\n}\n\n");
    for (name, schema) in schemas {
        let name = identifier(name.as_str().ok_or("schema name is not text")?)?;
        if schema.get("type").and_then(Value::as_str) == Some("object") {
            let Some(properties) = schema.get("properties").and_then(Value::as_mapping) else {
                writeln!(out, "pub type {name} = serde_json::Value;\n")
                    .map_err(|e| e.to_string())?;
                continue;
            };
            out.push_str("#[derive(Clone, serde::Serialize, serde::Deserialize)]\n");
            if schema.get("additionalProperties").and_then(Value::as_bool) == Some(false) {
                out.push_str("#[serde(deny_unknown_fields)]\n");
            }
            write!(out, "pub struct {name} {{").map_err(|e| e.to_string())?;
            if !properties.is_empty() {
                out.push('\n');
            }
            let required: BTreeSet<_> = schema
                .get("required")
                .and_then(Value::as_sequence)
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .collect();
            for (field, value) in properties {
                let field = identifier(field.as_str().ok_or("field is not text")?)?;
                let mut kind = rust_type(value)?;
                if !required.contains(field) && !kind.starts_with("Option<") {
                    kind = format!("Option<{kind}>");
                }
                writeln!(out, "    pub r#{field}: {kind},").map_err(|e| e.to_string())?;
            }
            out.push_str("}\n\n");
            writeln!(out, "impl ApiModel for {name} {{\n    const SCHEMA_NAME: &'static str = \"{name}\";\n}}\n").map_err(|e| e.to_string())?;
        } else {
            writeln!(out, "pub type {name} = {};\n", rust_type(schema)?)
                .map_err(|e| e.to_string())?;
        }
    }
    Ok(format!("{}\n", out.trim_end()))
}

fn identifier(text: &str) -> Result<&str, String> {
    if text.is_empty()
        || !text.bytes().all(|c| c.is_ascii_alphanumeric() || c == b'_')
        || text.as_bytes()[0].is_ascii_digit()
    {
        return Err("OpenAPI name cannot be represented as a Rust identifier".into());
    }
    Ok(text)
}

fn rust_type(schema: &Value) -> Result<String, String> {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return Ok(identifier(super::component_name(reference)?)?.into());
    }
    if let Some(options) = schema.get("oneOf").and_then(Value::as_sequence) {
        if options.len() == 2
            && options
                .iter()
                .any(|v| v.get("type").and_then(Value::as_str) == Some("null"))
        {
            let other = options
                .iter()
                .find(|v| v.get("type").and_then(Value::as_str) != Some("null"))
                .ok_or("invalid nullable union")?;
            return Ok(format!("Option<{}>", rust_type(other)?));
        }
        return Ok("serde_json::Value".into());
    }
    if let Some(kinds) = schema.get("type").and_then(Value::as_sequence) {
        if kinds.len() == 2 && kinds.iter().any(|v| v.as_str() == Some("null")) {
            let kind = kinds
                .iter()
                .find_map(|v| v.as_str().filter(|s| *s != "null"))
                .ok_or("invalid nullable schema")?;
            return Ok(format!("Option<{}>", named_type(kind, schema)?));
        }
        return Err("unsupported Rust union type".into());
    }
    named_type(
        schema
            .get("type")
            .and_then(Value::as_str)
            .ok_or("schema type absent")?,
        schema,
    )
}

fn named_type(kind: &str, schema: &Value) -> Result<String, String> {
    Ok(match kind {
        "string" => "String".into(),
        "boolean" => "bool".into(),
        "integer" => {
            if schema
                .get("minimum")
                .and_then(Value::as_i64)
                .is_some_and(|n| n >= 0)
                || schema.get("format").and_then(Value::as_str) == Some("uint64")
            {
                "u64".into()
            } else {
                "i64".into()
            }
        }
        "number" => "f64".into(),
        "null" => "()".into(),
        "array" => format!(
            "Vec<{}>",
            rust_type(schema.get("items").ok_or("array items absent")?)?
        ),
        "object" => "serde_json::Value".into(),
        _ => return Err("unsupported Rust schema type".into()),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn rust_models_and_schema_preserve_required_closed_nullable_and_references() {
        let artifacts = artifacts().unwrap();
        let rust = &artifacts[0].1;
        assert!(rust.contains("pub struct OperatorSnapshot {"));
        assert!(rust.contains("pub r#data: OperatorSnapshotView,"));
        assert!(rust.contains("pub r#ready: Option<ReadyView>,"));
        let schema: serde_json::Value = serde_json::from_str(&artifacts[1].1).unwrap();
        assert_eq!(
            schema["$defs"]["OperatorSnapshotView"]["additionalProperties"],
            false
        );
        assert_eq!(
            schema["$defs"]["BootstrapResponse"]["properties"]["csrf_token"]["pattern"],
            "^csrf_[0-9a-f]{64}$"
        );
        assert!(!artifacts[1].1.contains("#/components/schemas/"));
        assert!(identifier("evil; injected").is_err());
    }
}
