//! Deterministic TypeScript generation from `contracts/openapi.yaml`.
//! The YAML is the source of truth; `check` regenerates in memory and diffs.

use serde_json::{json, Map as JsonMap, Value as JsonValue};
use serde_yaml::{Mapping, Value};
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

const HEADER: &str = "/* generated by `bullet contracts generate`\n\
                      \x20* source: contracts/openapi.yaml\n\
                      \x20* regenerate: cargo run -p bullet -- contracts generate\n\
                      \x20* do not hand-edit */\n\n";
const RUNTIME_SCHEMA_ID: &str = "https://bullet.farm/schemas/public-api-runtime-v1";
const RUNTIME_SCHEMA_ROOTS: &[&str] = &[
    "AuditView",
    "BootstrapResponse",
    "CommandStatus",
    "ContextLineageView",
    "EventEnvelope",
    "FleetView",
    "Health",
    "MergeRailView",
    "Mission",
    "MissionView",
    "OutboxView",
    "Problem",
    "QualityLabView",
    "ReadyView",
    "SessionSupervisorView",
];
const COMPONENT_REF_PREFIX: &str = "#/components/schemas/";

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// Write `contracts/generated/api.ts` from the YAML contract.
///
/// # Errors
///
/// Returns a message when the YAML is unreadable or unsupported.
pub fn generate() -> Result<(), String> {
    let out_path = repo_root().join("contracts/generated/api.ts");
    let rendered = render()?;
    std::fs::write(&out_path, rendered)
        .map_err(|err| format!("write {}: {err}", out_path.display()))?;
    println!("contracts generate: wrote {}", out_path.display());
    Ok(())
}

/// Regenerate in memory and compare with the committed file.
///
/// # Errors
///
/// Returns a message when the committed file is stale or missing.
pub fn check() -> Result<(), String> {
    let out_path = repo_root().join("contracts/generated/api.ts");
    let expected = render()?;
    let current = std::fs::read_to_string(&out_path)
        .map_err(|err| format!("read {}: {err}", out_path.display()))?;
    if current != expected {
        let diff_line = first_difference(&current, &expected);
        return Err(format!(
            "contracts/generated/api.ts is stale (first difference at line {diff_line}); \
             run `cargo run -p bullet -- contracts generate`"
        ));
    }
    println!("contracts check: up to date");
    Ok(())
}

fn first_difference(current: &str, expected: &str) -> usize {
    for (idx, (a, b)) in current.lines().zip(expected.lines()).enumerate() {
        if a != b {
            return idx + 1;
        }
    }
    current.lines().count().min(expected.lines().count()) + 1
}

fn render() -> Result<String, String> {
    let yaml_path = repo_root().join("contracts/openapi.yaml");
    let text = std::fs::read_to_string(&yaml_path)
        .map_err(|err| format!("read {}: {err}", yaml_path.display()))?;
    let doc: Value =
        serde_yaml::from_str(&text).map_err(|err| format!("parse openapi.yaml: {err}"))?;
    let schemas = doc
        .get("components")
        .and_then(|components| components.get("schemas"))
        .and_then(Value::as_mapping)
        .ok_or("openapi.yaml has no components.schemas")?;
    let mut out = String::from(HEADER);
    for (name, schema) in schemas {
        let name = name
            .as_str()
            .ok_or_else(|| format!("schema name {name:?} is not a string"))?;
        let body = ts_type(schema, 0).map_err(|err| format!("schema {name}: {err}"))?;
        writeln!(out, "export type {name} = {body};\n").map_err(|err| err.to_string())?;
    }
    let runtime_schema = runtime_schema(schemas)?;
    let runtime_json =
        serde_json::to_string_pretty(&runtime_schema).map_err(|err| err.to_string())?;
    writeln!(
        out,
        "export const PUBLIC_API_RUNTIME_SCHEMA = {runtime_json} as const;\n"
    )
    .map_err(|err| err.to_string())?;
    out.push_str("export const PUBLIC_API_RUNTIME_REFS = {\n");
    for root in RUNTIME_SCHEMA_ROOTS {
        writeln!(out, "  {root}: \"{RUNTIME_SCHEMA_ID}#/$defs/{root}\",")
            .map_err(|err| err.to_string())?;
    }
    out.push_str("} as const;\n\n");
    out.push_str("export const API_PREFIX = \"/api/v1\";\n");
    Ok(out)
}

fn runtime_schema(schemas: &Mapping) -> Result<JsonValue, String> {
    let names = runtime_schema_names(schemas)?;
    let mut definitions = JsonMap::new();
    for name in names {
        let schema = schema_named(schemas, &name)?;
        let mut json = serde_json::to_value(schema)
            .map_err(|err| format!("serialize runtime schema {name}: {err}"))?;
        rewrite_component_refs(&mut json)?;
        definitions.insert(name, json);
    }
    Ok(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": RUNTIME_SCHEMA_ID,
        "$defs": definitions,
    }))
}

fn runtime_schema_names(schemas: &Mapping) -> Result<BTreeSet<String>, String> {
    let mut names = BTreeSet::new();
    let mut pending = RUNTIME_SCHEMA_ROOTS
        .iter()
        .map(ToString::to_string)
        .collect::<Vec<_>>();
    while let Some(name) = pending.pop() {
        if !names.insert(name.clone()) {
            continue;
        }
        collect_component_refs(schema_named(schemas, &name)?, &mut pending)?;
    }
    Ok(names)
}

fn schema_named<'a>(schemas: &'a Mapping, name: &str) -> Result<&'a Value, String> {
    schemas
        .get(Value::String(name.to_owned()))
        .ok_or_else(|| format!("runtime schema references absent component {name}"))
}

fn collect_component_refs(value: &Value, refs: &mut Vec<String>) -> Result<(), String> {
    match value {
        Value::Mapping(mapping) => {
            for (key, value) in mapping {
                if key.as_str() == Some("$ref") {
                    let raw = value
                        .as_str()
                        .ok_or_else(|| format!("non-string runtime schema $ref {value:?}"))?;
                    refs.push(component_name(raw)?.to_owned());
                }
                collect_component_refs(value, refs)?;
            }
        }
        Value::Sequence(sequence) => {
            for value in sequence {
                collect_component_refs(value, refs)?;
            }
        }
        _ => {}
    }
    Ok(())
}

fn rewrite_component_refs(value: &mut JsonValue) -> Result<(), String> {
    match value {
        JsonValue::Object(mapping) => {
            if let Some(reference) = mapping.get_mut("$ref") {
                let raw = reference
                    .as_str()
                    .ok_or_else(|| format!("non-string runtime schema $ref {reference:?}"))?;
                *reference = JsonValue::String(format!("#/$defs/{}", component_name(raw)?));
            }
            for value in mapping.values_mut() {
                rewrite_component_refs(value)?;
            }
        }
        JsonValue::Array(sequence) => {
            for value in sequence {
                rewrite_component_refs(value)?;
            }
        }
        _ => {}
    }
    Ok(())
}

fn component_name(reference: &str) -> Result<&str, String> {
    let name = reference
        .strip_prefix(COMPONENT_REF_PREFIX)
        .ok_or_else(|| format!("runtime schema has external or unsupported $ref {reference}"))?;
    if name.is_empty() || name.contains('/') {
        return Err(format!(
            "runtime schema has malformed component $ref {reference}"
        ));
    }
    Ok(name)
}

fn ts_type(schema: &Value, indent: usize) -> Result<String, String> {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference
            .rsplit('/')
            .next()
            .map(str::to_string)
            .ok_or_else(|| format!("unsupported $ref {reference}"));
    }
    if let Some(options) = schema.get("enum").and_then(Value::as_sequence) {
        let mut parts = Vec::new();
        for option in options {
            let literal = option
                .as_str()
                .ok_or_else(|| format!("non-string enum member {option:?}"))?;
            parts.push(format!("\"{literal}\""));
        }
        return Ok(parts.join(" | "));
    }
    if let Some(options) = schema.get("oneOf").and_then(Value::as_sequence) {
        let parts = options
            .iter()
            .map(|option| ts_type(option, indent))
            .collect::<Result<Vec<_>, _>>()?;
        return Ok(parts.join(" | "));
    }
    match schema.get("type") {
        Some(Value::String(kind)) => named_type(kind, schema, indent),
        Some(Value::Sequence(kinds)) => {
            let mut parts = Vec::new();
            for kind in kinds {
                let kind = kind
                    .as_str()
                    .ok_or_else(|| format!("non-string type entry {kind:?}"))?;
                parts.push(named_type(kind, schema, indent)?);
            }
            Ok(parts.join(" | "))
        }
        _ => Err("schema has no $ref, enum, oneOf, or type".into()),
    }
}

fn named_type(kind: &str, schema: &Value, indent: usize) -> Result<String, String> {
    match kind {
        "string" => Ok("string".into()),
        "integer" | "number" => Ok("number".into()),
        "boolean" => Ok("boolean".into()),
        "null" => Ok("null".into()),
        "array" => {
            let items = schema.get("items").ok_or("array schema without items")?;
            Ok(format!("{}[]", ts_type(items, indent)?))
        }
        "object" => object_type(schema, indent),
        other => Err(format!("unsupported type {other}")),
    }
}

fn object_type(schema: &Value, indent: usize) -> Result<String, String> {
    let properties = schema
        .get("properties")
        .and_then(Value::as_mapping)
        .ok_or("object schema without properties")?;
    let required: BTreeSet<&str> = schema
        .get("required")
        .and_then(Value::as_sequence)
        .map(|entries| entries.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let pad = "  ".repeat(indent);
    let mut out = String::from("{\n");
    for (prop, prop_schema) in properties {
        let prop = prop
            .as_str()
            .ok_or_else(|| format!("property name {prop:?} is not a string"))?;
        let marker = if required.contains(prop) { "" } else { "?" };
        let value = ts_type(prop_schema, indent + 1)?;
        writeln!(out, "{pad}  {prop}{marker}: {value};").map_err(|err| err.to_string())?;
    }
    write!(out, "{pad}}}").map_err(|err| err.to_string())?;
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn openapi_schemas() -> Mapping {
        let text = std::fs::read_to_string(repo_root().join("contracts/openapi.yaml"))
            .expect("read OpenAPI");
        let doc: Value = serde_yaml::from_str(&text).expect("parse OpenAPI");
        doc.get("components")
            .and_then(|components| components.get("schemas"))
            .and_then(Value::as_mapping)
            .expect("component schemas")
            .clone()
    }

    #[test]
    fn runtime_schema_is_strict_closed_and_internal() {
        let bundle = runtime_schema(&openapi_schemas()).expect("runtime schema");
        assert_eq!(
            bundle.pointer("/$defs/CommandId/pattern"),
            Some(&JsonValue::String("^cmd_[0-9a-f]{64}$".into()))
        );
        assert_eq!(
            bundle.pointer("/$defs/RepositoryId/pattern"),
            Some(&JsonValue::String("^rep_[0-9a-f]{64}$".into()))
        );
        for name in [
            "AttemptRow",
            "AuditEvent",
            "AuditView",
            "BootstrapResponse",
            "CandidateRow",
            "CommandStatus",
            "ContextCapsuleRow",
            "ContextLineageView",
            "EffectIntentRow",
            "EffectReceiptRow",
            "EffectRow",
            "EvidenceRow",
            "EventEnvelope",
            "FleetLease",
            "FleetView",
            "Health",
            "HealthReap",
            "LabelCount",
            "LeaseEventRef",
            "MergeRailView",
            "Mission",
            "MissionView",
            "OutboxItem",
            "OutboxView",
            "Problem",
            "QualityLabView",
            "ReadyRow",
            "ReadyView",
            "SessionSupervisorView",
            "WorkPackage",
        ] {
            assert_eq!(
                bundle.pointer(&format!("/$defs/{name}/additionalProperties")),
                Some(&JsonValue::Bool(false))
            );
        }
        assert_eq!(
            bundle.pointer("/$defs/EventEnvelope/properties/at/format"),
            Some(&JsonValue::String("date-time".into()))
        );
        assert_eq!(
            bundle.pointer("/$defs/EventEnvelope/properties/id/pattern"),
            Some(&JsonValue::String("^[0-9a-f]{64}$".into()))
        );
        assert_eq!(
            bundle.pointer("/$defs/EventEnvelope/properties/seq/maximum"),
            Some(&JsonValue::from(9_007_199_254_740_991_u64))
        );
        assert_eq!(
            bundle.pointer("/$defs/Health/properties/reap/$ref"),
            Some(&JsonValue::String("#/$defs/HealthReap".into()))
        );
        assert_eq!(
            bundle.pointer("/$defs/OutboxItem/properties/phase/enum"),
            Some(&json!([
                "pending", "applied", "failed", "verified", "unknown"
            ]))
        );
        assert_eq!(
            bundle.pointer("/$defs/Problem/properties/status/minimum"),
            Some(&JsonValue::from(400))
        );
        for root in [
            "BootstrapResponse",
            "EventEnvelope",
            "Health",
            "OutboxView",
            "Problem",
        ] {
            assert!(RUNTIME_SCHEMA_ROOTS.contains(&root));
            assert!(bundle.pointer(&format!("/$defs/{root}")).is_some());
        }
        assert!(bundle.pointer("/$defs/DemoReceipt").is_none());
        assert!(!serde_json::to_string(&bundle)
            .expect("serialize bundle")
            .contains(COMPONENT_REF_PREFIX));
        assert!(component_name("https://example.invalid/schema").is_err());
        assert!(component_name("#/components/schemas/").is_err());
        assert!(component_name("#/components/schemas/Mission/id").is_err());
    }

    #[test]
    fn context_lineage_runtime_root_closes_the_task_class_catalog() {
        let bundle = runtime_schema(&openapi_schemas()).expect("runtime schema");
        let task_classes = bundle
            .pointer("/$defs/TaskClass/enum")
            .and_then(JsonValue::as_array)
            .expect("TaskClass enum");
        assert_eq!(
            task_classes,
            &[
                "deterministic_transform",
                "extract_structured",
                "classify_route",
                "summarize_local",
                "compress_context",
                "mechanical_code_edit",
                "bounded_bug_fix",
                "feature_implementation",
                "broad_refactor",
                "architecture_design",
                "security_analysis",
                "migration_design",
                "code_review",
                "fusion_rank",
                "fusion_synthesize",
                "completion_assessment",
            ]
            .map(JsonValue::from)
        );
        assert_eq!(
            bundle.pointer("/$defs/ContextCapsuleRow/properties/task_class/$ref"),
            Some(&JsonValue::String("#/$defs/TaskClass".into()))
        );
        assert!(RUNTIME_SCHEMA_ROOTS.contains(&"ContextLineageView"));
    }
}
