//! Optional Portal embedding.
//!
//! Without the `embedded-portal` feature this script only records its rerun
//! keys: the default build compiles no static assets, needs no Node, and
//! mounts no static route. With the feature it requires `BULLET_PORTAL_DIST`
//! to name an absolute, already-built `bullet-portal` `dist/` directory,
//! verifies every byte against that directory's own bundle manifest, and
//! stages only verified bytes into `OUT_DIR`. Any drift, extra entry, symlink,
//! or non-canonical manifest fails the build with the verifier's typed
//! refusal code; no `dist` is ever committed to this repository.

#[cfg(feature = "embedded-portal")]
#[path = "build/bundle.rs"]
mod bundle;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build/bundle.rs");
    println!("cargo:rerun-if-changed=build/manifest.rs");
    println!("cargo:rerun-if-changed=build/records.rs");
    println!("cargo:rerun-if-env-changed=BULLET_PORTAL_DIST");
    #[cfg(feature = "embedded-portal")]
    embed();
}

#[cfg(feature = "embedded-portal")]
fn embed() {
    use std::path::{Path, PathBuf};

    let Ok(dist) = std::env::var("BULLET_PORTAL_DIST") else {
        refuse(
            "PORTAL_DIST_REQUIRED",
            "feature embedded-portal needs BULLET_PORTAL_DIST=<absolute bullet-portal dist>",
        );
    };
    let dist = PathBuf::from(dist);
    let bundle = match bundle::verify(&dist) {
        Ok(bundle) => bundle,
        Err(refusal) => refuse(refusal.code, &refusal.detail),
    };
    println!("cargo:rerun-if-changed={}", dist.display());
    println!(
        "cargo:rerun-if-changed={}",
        dist.join(bundle::MANIFEST_NAME).display()
    );
    let out_dir = PathBuf::from(expect_env("OUT_DIR"));
    let staged = out_dir.join("portal");
    if staged.exists() {
        expect_io(std::fs::remove_dir_all(&staged), "clear staged bundle");
    }
    expect_io(
        std::fs::create_dir_all(staged.join("assets")),
        "create staged bundle",
    );
    let mut generated =
        String::from("// Generated by build.rs from a manifest-verified bullet-portal dist.\n");
    generated.push_str(&format!(
        "pub(super) const ROOT: &str = {:?};\npub(super) const SOURCE_COMMIT: &str = {:?};\npub(super) const SOURCE_TREE: &str = {:?};\npub(super) const FILES: &[EmbeddedFile] = &[\n",
        bundle.root, bundle.commit_oid, bundle.tree_oid
    ));
    for file in &bundle.files {
        println!("cargo:rerun-if-changed={}", dist.join(&file.path).display());
        let target = staged.join(&file.path);
        expect_io(std::fs::write(&target, &file.body), "stage bundle file");
        generated.push_str(&format!(
            "    EmbeddedFile {{ path: {:?}, mime: {:?}, etag: {:?}, body: include_bytes!({:?}) }},\n",
            file.path,
            file.mime,
            format!("\"blake3-{}\"", file.digest_hex),
            absolute(&target),
        ));
    }
    generated.push_str("];\n");
    expect_io(
        std::fs::write(out_dir.join("portal_bundle.rs"), generated),
        "write generated bundle",
    );

    fn absolute(path: &Path) -> String {
        path.to_str()
            .unwrap_or_else(|| refuse("PORTAL_DIST_NOT_UTF8", "staged path is not UTF-8"))
            .to_string()
    }
}

/// Fail the build with a typed refusal code and a safe detail.
#[cfg(feature = "embedded-portal")]
fn refuse(code: &str, detail: &str) -> ! {
    panic!("bullet-farmd: embedded-portal: {code}: {detail}");
}

#[cfg(feature = "embedded-portal")]
fn expect_env(key: &str) -> String {
    match std::env::var(key) {
        Ok(value) => value,
        Err(error) => refuse("BUILD_ENVIRONMENT", &format!("{key}: {error}")),
    }
}

#[cfg(feature = "embedded-portal")]
fn expect_io<T>(result: std::io::Result<T>, action: &str) -> T {
    match result {
        Ok(value) => value,
        Err(error) => refuse("STAGING_FAILED", &format!("{action}: {error}")),
    }
}
